"""
Django settings for codepost project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime
import sys

import urllib
from celery.schedules import crontab
import django
from django.utils.translation import gettext
django.utils.translation.ugettext = gettext
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


################## Autograder settings ##############################

# Autograder URL
# This is the URL where the autograder service is running.
# Used for communication between the API and the autograder.

AUTOGRADER_URL = "https://4bppxuryyz.codepost.io"
# AUTOGRADER_URL = "https://qoe9ev62y5.codepost.io"
# AUTOGRADER_URL = "http://127.0.0.1:8002"
# AUTOGRADER_URL = "https://autograder-cyl1.onrender.com"

################## Celery settings ##############################
# Adding celery. To set up locally do the following commands:
#
# > pip install -r requirements.txt
# > PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
#
# The reason for the PYCURL command is that MacOSX uses a different ssl backend than our linux server.
#
# To run the worker locally, run the following in a second terminal:
# > celery worker -A autograder --loglevel=info -Q dev-api-celery,dev-api-celery-long-tasks

# if "SQS_ACCESS" in os.environ:
#     CELERY_DEFAULT_QUEUE = "prod-celery"
#     CELERY_ROUTES = {
#         "autograder.tasks.RunAll": {"queue": "prod-celery-long-tasks"},
#         "autograder.tasks.daily_assignment_check": {"queue": "prod-celery-crontasks"},
#         "webhooks.tasks.DeliverHook": {"queue": "prod-celery-webhooks"},
#     }
#     SQS_ACCESS = os.environ["SQS_ACCESS"]
#     SQS_SECRET = os.environ["SQS_SECRET"]


# else:
#     # This Access Credentials is for a user that only has access to the dev queues specified
#     SQS_ACCESS = "AKIAV22BSJSCUAENRZH6"
#     SQS_SECRET = "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"
#     CELERY_DEFAULT_QUEUE = "dev-api-celery"
#     CELERY_ROUTES = {
#         "autograder.tasks.RunAll": {"queue": "dev-api-celery-long-tasks"},
#     }

CELERY_DEFAULT_QUEUE = "prod-celery"
# CELERY_ROUTES = {
#     "autograder.tasks.RunAll": {"queue": "prod-celery"},
#     # "autograder.tasks.daily_assignment_check": {"queue": "prod-celery-crontasks"},
#     # "webhooks.tasks.DeliverHook": {"queue": "prod-celery-webhooks"},
# }

# BROKER_URL = os.getenv("CELERY_BROKER_URL")
# BROKER_URL = "sqs://{aws_access_key}:{aws_secret_key}@".format(
#     aws_access_key=urllib.parse.quote(SQS_ACCESS, safe=''), aws_secret_key=urllib.parse.quote(SQS_SECRET, safe=''),
# )

DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_IGNORE_RESULT = False
CELERY_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
# CELERYBEAT_SCHEDULE = {
#     "daily-assignment-check": {
#         "task": "autograder.run.daily_assignment_check",
#         "schedule": crontab(day_of_week="*", hour="14", minute="1"),
#     }
# }
BROKER_TRANSPORT_OPTIONS = {
    # "region": "us-east-2",
    "polling_interval": 20,
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default="your secret key")

# Check if the application should run in debug mode
# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get("RENDER", False)  is True and os.environ.get("PRODUCTION_MODE", False)  is True:
    DEBUG = False
else:
    DEBUG = True

# if "RENDER" in os.environ and "PRODUCTION_MODE" in os.environ:
#     DEBUG = False
# else:
#     DEBUG = True

# Testing flag
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

ALLOWED_HOSTS = [
    "codepost-api-dev.pexarpdmjm.us-east-2.elasticbeanstalk.com",
    "codepost-api-production.pexarpdmjm.us-east-2.elasticbeanstalk.com",
    "api.codepost-labs.io",
    "localhost",
    "127.0.0.1",
    "*",
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition
from webhooks.codepost_hooks import codepost_hooks

HOOK_EVENTS = codepost_hooks
HOOK_DELIVERER = "webhooks.tasks.deliver_hook_wrapper"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "viewflow",
    "core",
    "mooc",
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    "django_extensions",
    "django_celery_results",
    "webhooks",
    "log",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if DEBUG:
    MIDDLEWARE.append("core.middleware.dev_cors_middleware")

ROOT_URLCONF = "codepost.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "codepost/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "codepost.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if "RDS_HOSTNAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["RDS_DB_NAME"],
            "USER": os.environ["RDS_USERNAME"],
            "PASSWORD": os.environ["RDS_PASSWORD"],
            "HOST": os.environ["RDS_HOSTNAME"],
            "PORT": os.environ["RDS_PORT"],
            "OPTIONS": {"charset": "utf8mb4"},
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

# https://rickchristianson.wordpress.com/2013/10/31/getting-a-django-app-to-use-https-on-aws-elastic-beanstalk/
if os.environ.get("ON_AWS", False) is True:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health-check/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "static"


if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# os.path.join(BASE_DIR, 'build/static'),

STATICFILES_DIRS = []

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        'rest_framework_simplejwt.authentication.JWTAuthentication',        
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ORIGIN_REGEX_WHITELIST = (r"^.*$",)

CSRF_TRUSTED_ORIGINS = (
    "http://localhost",
    "https://localhost",
    "http://*.cs.rutgers.edu",
    "https://*.cs.rutgers.edu",
)

SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "core.views.auth.JWTSerializer",
    "JWT_ALLOW_REFRESH": True,
    "JWT_EXPIRATION_DELTA": datetime.timedelta(days=7),
    "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.SlidingToken', 'rest_framework_simplejwt.tokens.AccessToken'),
}


if "ON_AWS" in os.environ:
    SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")
    if "SENDGRID_SANDBOX" in os.environ:
        SENDGRID_SANDBOX = True
    else:
        SENDGRID_SANDBOX = False
    if "SENDGRID_OVERRIDE_EMAIL" in os.environ:
        SENDGRID_OVERRIDE_EMAIL = os.environ.get("SENDGRID_OVERRIDE_EMAIL")
    else:
        SENDGRID_OVERRIDE_EMAIL = None
    CLIENT_URL = os.environ.get("CLIENT_URL")
    MOOC_CLIENT_URL = os.environ.get("MOOC_CLIENT_URL")
    API_URL = os.environ.get("API_URL")
else:
    SENDGRID_API_KEY = "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"  # can make this our 'test account'
    SENDGRID_SANDBOX = True
    SENDGRID_OVERRIDE_EMAIL = "richard+test@codepost.io"
    CLIENT_URL = "http://localhost:3000"
    MOOC_CLIENT_URL = "http://localhost:3001"
    API_URL = "http://localhost:8000"


EMAIL_HOST = "smtp.mailgun.org"
EMAIL_HOST_USER = "postmaster@sandbox62f8530fe8fe4f91b47ddbd740cc0e3e.mailgun.org"
EMAIL_HOST_PASSWORD = os.environ.get("MAILGUN_PASSWORD")
EMAIL_PORT = 587
ADMINS = [("codePost", "richard@codepost.io")]
EMAIL_USE_TLS = True
# SERVER_EMAIL = "team@coodepost.io"
# DEFAULT_FROM_EMAIL = "codePost Team <team@codepost.io>"
EMAIL_SUBJECT_PREFIX = "[Django] "
