"""
Django settings for codepost project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime
import sys
import socket
import urllib
from celery.schedules import crontab
from urllib.parse import urlparse
import regex
import structlog


def checkCSRFTrustedOrigins(CLIENT_URL, CSRF_TRUSTED_ORIGINS):
    """
    Check if the CSRF_TRUSTED_ORIGINS setting is set correctly.
    If not, print a warning message.
    """
    for origin in CSRF_TRUSTED_ORIGINS:
        if regex.match(origin, CLIENT_URL):
            return True
    print(f"WARNING: {CLIENT_URL} is not in CSRF_TRUSTED_ORIGINS. This may cause issues with CSRF protection.")
    return False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


######################### settings ##############################

# HOSTNAME (optional): The hostname of the machine running the codepost API.
# API_URL: The URL of the codepost API.
# CLIENT_URL: The URL of the codepost client.
# DEBUG (optional): Whether the codepost API is running in debug mode.
# TESTING (optional): Whether the codepost API is running in testing mode.
# SECRET_KEY: The secret key used for cryptographic signing.
# ON_AWS (optional): Whether the codepost API is running on AWS.
# DB_NAME: The name of the database used by the codepost API.
# DB_HOSTNAME: The hostname of the database used by the codepost API.
# DB_PORT: The port of the database used by the codepost API.
# DB_USERNAME: The username used to connect to the database.
# DB_PASSWORD: The password used to connect to the database.
# LOKI_URL: The URL of the Loki logging service.
# EMAIL_HOST: The hostname of the email service.
# EMAIL_PORT: The port of the email service.
# EMAIL_USE_TLS: Whether to use TLS for the email service.
# EMAIL_USE_SSL: Whether to use SSL for the email service.
# DEFAULT_EMAIL_FROM: The default email address used for sending emails.
# OVERRIDE_EMAIL (optional): If set, all emails will be sent to this address instead of the original recipient.
# CELERY_BROKER_URL: The URL of the Celery broker.

###################### Environment settings ##############################

DOCKER = os.path.exists('/.dockerenv')


#################### CodePost settings ##############################
# These settings are used to configure the CodePost application.

HOSTNAME = os.environ.get("HOSTNAME", socket.gethostname())
API_URL = os.environ.get("API_URL", "http://localhost:8000")
CLIENT_URL = os.environ.get("CLIENT_URL", "http://localhost:3000")
DEBUG = os.environ.get("DEBUG", "FALSE").upper() == "TRUE"
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
ADMINS = [
    ("LCSR Codepost Team", "mk1800@rutgers.edu"),
]

API_HOST = urlparse(API_URL).netloc.split(':')[0]

#################### Authentication And Host settings ##############################

SECRET_KEY = os.environ.get("SECRET_KEY", "your secret key")
if SECRET_KEY == "your secret key":
    # Secret key is used for cryptographic signing and should be kept secret in production.
    print("WARNING: You are using the default secret key. This is insecure and should not be used in production.")


# Allowed host settings
ALLOWED_HOSTS = [
    "codepost-api.cs.rutgers.edu",
    "128.6.13.52",  
    "172.16.71.211",
]

if DOCKER:
    ALLOWED_HOSTS.append(os.environ.get("API_HOSTNAME", "localhost"))

if DEBUG: 
    ALLOWED_HOSTS.append("localhost")
    ALLOWED_HOSTS.append("127.0.0.1")
    ALLOWED_HOSTS.append("*")
    print("WARNING: You are using a wildcard ALLOWED_HOSTS. This is insecure and should not be used in production.")

if not API_HOST in ALLOWED_HOSTS:
    print(f"WARNING: {API_HOST} is not in ALLOWED_HOSTS. This may cause issues with CORS and CSRF protection.") 




# https://rickchristianson.wordpress.com/2013/10/31/getting-a-django-app-to-use-https-on-aws-elastic-beanstalk/
if os.environ.get("ON_AWS", False) is True:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health-check/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

if DOCKER:
    # If running in Docker, we assume that the API is behind a reverse proxy
    # that handles SSL termination and forwards the request to the API.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health-check/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        'rest_framework_simplejwt.authentication.JWTAuthentication',        
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# CORS settings
# https://pypi.org/project/django-cors-headers/

CORS_ORIGIN_REGEX_WHITELIST = (r"^.*$",)

CSRF_TRUSTED_ORIGINS = (
    "http://localhost",
    "https://localhost",
    "http://*.cs.rutgers.edu",
    "https://*.cs.rutgers.edu",
)

checkCSRFTrustedOrigins(CLIENT_URL, CSRF_TRUSTED_ORIGINS)

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "core.views.auth.JWTSerializer",
    "JWT_ALLOW_REFRESH": True,
    "JWT_EXPIRATION_DELTA": datetime.timedelta(days=7),
    "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.SlidingToken', 'rest_framework_simplejwt.tokens.AccessToken'),
}

################# End Authentication settings ##############################

################# Database and Model settings ##############################

# Model settings
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if "RDS_HOSTNAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["RDS_DB_NAME"],
            "USER": os.environ["RDS_USERNAME"],
            "PASSWORD": os.environ["RDS_PASSWORD"],
            "HOST": os.environ["RDS_HOSTNAME"],
            "PORT": os.environ["RDS_PORT"],
            "OPTIONS": {"charset": "utf8mb4"},
            "CONN_MAX_AGE": 60,
        }
    }
elif "DB_HOSTNAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USERNAME"] if "DB_USERNAME" in os.environ else "root",
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ["DB_HOSTNAME"],
            "PORT": os.environ["DB_PORT"],
            "OPTIONS": {"charset": "utf8mb4"},
            "CONN_MAX_AGE": 60,
        }
    }
else:
    # Use SQLite for development and testing
    # This is not recommended for production use, but is fine for local development.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }


################# End Database settings ##############################

################## Email settings ##############################


# # Email settings

if DEBUG:
    OVERRIDE_EMAIL = os.environ.get("OVERRIDE_EMAIL", None)
else:
    OVERRIDE_EMAIL = None

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST", "mx.farside.rutgers.edu")
EMAIL_PORT = os.environ.get("EMAIL_PORT", 25)
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "TRUE").upper() == "TRUE"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "FALSE").upper() == "TRUE"
DEFAULT_EMAIL_FROM = os.environ.get("DEFAULT_EMAIL_FROM", "help@cs.rutgers.edu")
EMAIL_SUBJECT_PREFIX = "[Codepost] "


###################### End Email settings ##############################

################## Django settings ##############################

from webhooks.codepost_hooks import codepost_hooks

HOOK_EVENTS = codepost_hooks
HOOK_DELIVERER = "webhooks.tasks.deliver_hook_wrapper"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "viewflow",
    "core",
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    "django_extensions",
    "django_celery_results",
    "webhooks",
    "log",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if DEBUG:
    MIDDLEWARE.append("core.middleware.dev_cors_middleware")

ROOT_URLCONF = "codepost.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "codepost/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "codepost.wsgi.application"

# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "static"

if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = []




################## Logging settings ##############################


LOKI_URL = os.environ.get("LOKI_URL", "http://localhost:3100/loki/api/v1/push")

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
         'json': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.processors.JSONRenderer(),
        },
        'console': {
            'format': '%(levelname)s %(asctime)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'loki': {
            'level': 'INFO',
            'class': 'core.logging.LokiHandler', 
            'formatter': 'json',
        },
        "console": {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            "formatter":'console',
        },
    },
    'root': {
        'handlers': ['loki', 'console'],
        'level': 'INFO',
    },
}

################## End Logging settings ##############################

################## End Codepost settings ##############################

################## Autograder settings ##############################

# Autograder URL
# This is the URL where the autograder service is running.
# Used for communication between the API and the autograder.

AUTOGRADER_URL = "https://4bppxuryyz.codepost.io"
# AUTOGRADER_URL = "https://qoe9ev62y5.codepost.io"
# AUTOGRADER_URL = "http://127.0.0.1:8002"
# AUTOGRADER_URL = "https://autograder-cyl1.onrender.com"

################# Autograder settings end ##############################


################## Celery settings ##############################
# Adding celery. To set up locally do the following commands:
#
# > pip install -r requirements.txt
# > PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
#
# The reason for the PYCURL command is that MacOSX uses a different ssl backend than our linux server.
#
# To run the worker locally, run the following in a second terminal:
# > celery worker -A autograder --loglevel=info -Q dev-api-celery,dev-api-celery-long-tasks

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://codepost-redis:6379")
CELERY_DEFAULT_QUEUE = "prod-celery"
# CELERY_ROUTES = {
#     "autograder.tasks.RunAll": {"queue": "prod-celery"},
#     # "autograder.tasks.daily_assignment_check": {"queue": "prod-celery-crontasks"},
#     # "webhooks.tasks.DeliverHook": {"queue": "prod-celery-webhooks"},
# }

DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_IGNORE_RESULT = False
CELERY_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
# CELERYBEAT_SCHEDULE = {
#     "daily-assignment-check": {
#         "task": "autograder.run.daily_assignment_check",
#         "schedule": crontab(day_of_week="*", hour="14", minute="1"),
#     }
# }
BROKER_TRANSPORT_OPTIONS = {
    # "region": "us-east-2",
    "polling_interval": 20,
}

#################### End Celery settings ##############################


#################### Log info to console for debugging ##############################

print(f"CodePost API running on {API_URL}")
print(f"CodePost Client running on {CLIENT_URL}")
print(f"CodePost API running in {'debug' if DEBUG else 'production'} mode")
print(f"CodePost API Admins are {', '.join([f'{name} <{email}>' for name, email in ADMINS])}")

