# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
"""
Django settings for codepost project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import datetime
import sys
import socket
import urllib
from celery.schedules import crontab
from urllib.parse import urlparse
import regex
import structlog
import mimetypes

# Fix for .mjs files serving with wrong mime type
mimetypes.add_type("application/javascript", ".mjs", True)

logger = structlog.get_logger(__name__)


def checkCSRFTrustedOrigins(CLIENT_URL, CSRF_TRUSTED_ORIGINS):
    """
    Check if the CSRF_TRUSTED_ORIGINS setting is set correctly.
    If not, log a warning message.
    """
    for origin in CSRF_TRUSTED_ORIGINS:
        if regex.match(origin, CLIENT_URL):
            return True
    logger.warning(
        "csrf_trusted_origins_mismatch",
        client_url=CLIENT_URL,
        message="Client URL is not in CSRF_TRUSTED_ORIGINS. This may cause issues with CSRF protection."
    )
    return False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


######################### settings ##############################

# HOSTNAME (optional): The hostname of the machine running the codepost API.
# API_URL: The URL of the codepost API.
# CLIENT_URL: The URL of the codepost client.
# DEBUG (optional): Whether the codepost API is running in debug mode.
# TESTING (optional): Whether the codepost API is running in testing mode.
# SECRET_KEY: The secret key used for cryptographic signing.
# ON_AWS (optional): Whether the codepost API is running on AWS.
# DB_NAME: The name of the database used by the codepost API.
# DB_HOSTNAME: The hostname of the database used by the codepost API.
# DB_PORT: The port of the database used by the codepost API.
# DB_USERNAME: The username used to connect to the database.
# DB_PASSWORD: The password used to connect to the database.
# LOKI_URL: The URL of the Loki logging service.
# EMAIL_HOST: The hostname of the email service.
# EMAIL_PORT: The port of the email service.
# EMAIL_USE_TLS: Whether to use TLS for the email service.
# EMAIL_USE_SSL: Whether to use SSL for the email service.
# DEFAULT_EMAIL_FROM: The default email address used for sending emails.
# OVERRIDE_EMAIL (optional): If set, all emails will be sent to this address instead of the original recipient.
# CELERY_BROKER_URL: The URL of the Celery broker.

###################### Environment settings ##############################

DOCKER = os.path.exists('/.dockerenv')


#################### CodePost settings ##############################
# These settings are used to configure the CodePost application.

HOSTNAME = os.environ.get("HOSTNAME", socket.gethostname())
API_URL = os.environ.get("API_URL", "http://localhost:8000")
CLIENT_URL = os.environ.get("CLIENT_URL", "http://localhost:3000")
DEBUG = os.environ.get("DEBUG", "FALSE").upper() == "TRUE"
TESTING = os.environ.get("TESTING", "FALSE").upper() == "TRUE" or (len(sys.argv) > 1 and sys.argv[1] == "test")
ADMINS = [
    ("LCSR Codepost Team", "mk1800@rutgers.edu"),
]

# Internal shell relay (API -> worker)
WORKER_SHELL_WS_URL = os.environ.get("WORKER_SHELL_WS_URL", "")
WORKER_SHELL_SHARED_SECRET = os.environ.get("WORKER_SHELL_SHARED_SECRET", "")
WORKER_SHELL_REDIS_URL = os.environ.get("WORKER_SHELL_REDIS_URL", "")
WORKER_SHELL_FORCE_LOCAL = os.environ.get("WORKER_SHELL_FORCE_LOCAL", "FALSE").upper() == "TRUE"
WORKER_SHELL_WORKER_ID = os.environ.get("WORKER_SHELL_WORKER_ID", HOSTNAME)

API_HOST = urlparse(API_URL).netloc.split(':')[0]

#################### Authentication And Host settings ##############################

SECRET_KEY = os.environ.get("SECRET_KEY", "your secret key")
if SECRET_KEY == "your secret key":
    # Secret key is used for cryptographic signing and should be kept secret in production.
    logger.warning(
        "insecure_secret_key",
        message="You are using the default secret key. This is insecure and should not be used in production."
    )

# Encryption settings
FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY", "a8ZLWym0lKXZW2iwQw8mx3kdsX7EiGxjfznpPeGBZ4M=")


# Allowed host settings
ALLOWED_HOSTS = [
    "codepost-api.cs.rutgers.edu",
    "dev-codepost-2.cs.rutgers.edu",
    "128.6.13.52",  
    "172.16.71.211",
]

if DOCKER:
    ALLOWED_HOSTS.append(os.environ.get("API_HOSTNAME", "localhost"))

if DEBUG: 
    ALLOWED_HOSTS.append("localhost")
    ALLOWED_HOSTS.append("127.0.0.1")
    ALLOWED_HOSTS.append("*")
    logger.warning(
        "insecure_allowed_hosts",
        message="You are using a wildcard ALLOWED_HOSTS. This is insecure and should not be used in production."
    )

if not API_HOST in ALLOWED_HOSTS:
    logger.warning(
        "api_host_not_in_allowed_hosts",
        api_host=API_HOST,
        message="API host is not in ALLOWED_HOSTS. This may cause issues with CORS and CSRF protection."
    ) 





SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

if DOCKER:
    # If running in Docker, we assume that the API is behind a reverse proxy
    # that handles SSL termination and forwards the request to the API.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health-check/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

REST_FRAMEWORK = {
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        'rest_framework_simplejwt.authentication.JWTAuthentication',        
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'CAMELIZE_NAMES': True,
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'codepost.schema_hooks.restore_underscore_operation_ids',
    ],
    'TITLE': 'codePost API',
    'DESCRIPTION': """
An API for administrators to mine course data and automate common tasks.

## Quick Start

### Installation

```bash
pip install git+https://github.com/rutgers-lcsr/codepost-python.git
```

### Basic Usage

```python
import codepost_api_client as codepost

# Configure the client
config = codepost.Configuration(
    host="https://codepost-api.cs.rutgers.edu",
    api_key={"tokenAuth": "Token YOUR_API_KEY"}
)

# Use the API
with codepost.ApiClient(config) as client:
    courses_api = codepost.CoursesApi(client)
    assignments_api = codepost.AssignmentsApi(client)
    
    # 1. List all courses
    print("--- Courses ---")
    courses = courses_api.courses_list()
    for course in courses:
        print(f"ID: {course.id} | {course.name} ({course.period})")
        
    if courses:
        my_course_id = courses[0].id
        
        # 2. List assignments for a course
        # Note: Course object contains list of assignment IDs
        course_data = courses_api.courses_retrieve(my_course_id)
        
        print(f"--- Assignments for Course {my_course_id} ---")
        for assignment_id in course_data.assignments:
            # Fetch full assignment details
            assignment = assignments_api.assignments_retrieve(assignment_id)
            print(f"ID: {assignment.id} | {assignment.name}")

    # 3. Create a new Course
    new_course = codepost.Course(name="CS101", period="Fall 2026")
    created_course = courses_api.courses_create(new_course)
    print(f"Created Course: {created_course.id}")

    # 4. Create an Assignment
    new_assignment = codepost.Assignment(
        name="Homework 1", 
        course=created_course.id
    )
    created_assignment = assignments_api.assignments_create(new_assignment)
```

See the [Python SDK Repository](https://github.com/rutgers-lcsr/codepost-python) for more examples.
""",
    'VERSION': '3.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}

# CORS settings
# https://pypi.org/project/django-cors-headers/

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "Authorization",
    "Content-Type",
    "X-Requested-With",
    "Accept",
    "Origin",
    "User-Agent",
    "Referer",
    "Accept-Encoding",
    "Accept-Language",
    "DNT",
    "Connection",
    "Cookie",
    "If-Modified-Since",
    "Cache-Control",
    "Pragma",
    "X-CSRFToken",
]
CORS_ALLOW_METHODS = ["*"]

CSRF_TRUSTED_ORIGINS = (
    "http://localhost",
    "https://localhost",
    "http://*.cs.rutgers.edu",
    "https://*.cs.rutgers.edu",
    "https://dev-codepost-1.cs.rutgers.edu",
    "https://dev-codepost-2.cs.rutgers.edu",
    "https://codepost.cs.rutgers.edu",
)

checkCSRFTrustedOrigins(CLIENT_URL, CSRF_TRUSTED_ORIGINS)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "core.views.auth.JWTSerializer",
    "JWT_ALLOW_REFRESH": True,
    "JWT_EXPIRATION_DELTA": datetime.timedelta(days=7),
    "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.SlidingToken', 'rest_framework_simplejwt.tokens.AccessToken'),
}

################# End Authentication settings ##############################

################# Database and Model settings ##############################

# Model settings
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if "DB_HOSTNAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USERNAME"] if "DB_USERNAME" in os.environ else "root",
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ["DB_HOSTNAME"],
            "PORT": os.environ["DB_PORT"],
            "OPTIONS": {"charset": "utf8mb4"},
            "CONN_MAX_AGE": 60,
        }
    }
else:
    # Use SQLite for development and testing
    # This is not recommended for production use, but is fine for local development.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }


################# End Database settings ##############################

################## Email settings ##############################


# # Email settings

if DEBUG:
    OVERRIDE_EMAIL = os.environ.get("OVERRIDE_EMAIL", None)
else:
    OVERRIDE_EMAIL = None

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST", "mx.farside.rutgers.edu")
EMAIL_PORT = 25
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_EMAIL_FROM = os.environ.get("DEFAULT_EMAIL_FROM", "codepost@cs.rutgers.edu")
EMAIL_SUBJECT_PREFIX = "[Codepost] "


###################### End Email settings ##############################

################## Django settings ##############################

from webhooks.codepost_hooks import codepost_hooks

HOOK_EVENTS = codepost_hooks
HOOK_DELIVERER = "webhooks.tasks.deliver_hook_wrapper"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "viewflow",
    "core",
    "autograder",
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    "django_extensions",
    "django_celery_results",
    "webhooks",
    "log",
    "encrypted_model_fields",
    "drf_spectacular",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if DEBUG:
    MIDDLEWARE.append("core.middleware.dev_cors_middleware")

ROOT_URLCONF = "codepost.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "codepost/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "codepost.wsgi.application"
ASGI_APPLICATION = "codepost.asgi.application"

CHANNEL_LAYER_REDIS_URL = (
    os.environ.get("WORKER_SHELL_REDIS_URL")
    or os.environ.get("CELERY_BROKER_URL", "")
)

if CHANNEL_LAYER_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_LAYER_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "static"

# Only in docker 
if DOCKER:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = "/assignment_datasets"
else:
    # In local development
    MEDIA_URL = "/media/"
    MEDIA_ROOT = "assignment_datasets"

if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    

STATICFILES_DIRS = []

# X-Frame-Options

if DEBUG:
    X_FRAME_OPTIONS = 'SAMEORIGIN'
else:
    X_FRAME_OPTIONS = 'SAMEORIGIN'



################## Logging settings ##############################



structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(levelname)s %(asctime)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        "console": {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            "formatter":'console',
        },
    },
    'root': {
        'handlers': [ 'console'],
        'level': 'INFO',
    },
}


if DEBUG:
    LOGGING['root']['level'] = 'DEBUG'  # Set root logger level to DEBUG in debug mode

################## End Logging settings ##############################

################## End Codepost settings ##############################

################## Autograder settings ##############################

################# Autograder settings end ##############################


################## Celery settings ##############################
# Adding celery. To set up locally do the following commands:
#
# > pip install -r requirements.txt
# > PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
#
# The reason for the PYCURL command is that MacOSX uses a different ssl backend than our linux server.
#
# To run the worker locally, run the following in a second terminal:
# > celery worker -A autograder --loglevel=info -Q dev-api-celery,dev-api-celery-long-tasks


if DEBUG:
    CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379")
else:
    CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://codepost-redis:6379")

CELERY_DEFAULT_QUEUE = "prod-celery"
# CELERY_ROUTES = {
#     "autograder.tasks.RunAll": {"queue": "prod-celery"},
#     # "autograder.tasks.daily_assignment_check": {"queue": "prod-celery-crontasks"},
#     # "webhooks.tasks.DeliverHook": {"queue": "prod-celery-webhooks"},
# }

CELERY_BROKER_TRANSPORT_OPTIONS = {
    "priority_steps": list(range(10)),
}

DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH = 191
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_IGNORE_RESULT = False
CELERY_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
CELERY_BEAT_SCHEDULE = {
    # "daily-assignment-check": {
    #     "task": "autograder.run.daily_assignment_check",
    #     "schedule": crontab(day_of_week="*", hour="14", minute="1"),
    # },
    "delete-expired-courses": {
        "task": "core.tasks.delete_expired_courses",
        "schedule": crontab(minute=0, hour="*"), # Run every hour
    }
}
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "FALSE").upper() == "TRUE"
CELERY_TASK_STORE_EAGER_RESULT = True

BROKER_TRANSPORT_OPTIONS = {
    # "region": "us-east-2",
    "polling_interval": 20,
}

# Enable autograding tasks 
AUTOGRADER_AUTO_EXECUTE = os.environ.get("AUTOGRADER_AUTO_EXECUTE", "FALSE").upper() == "TRUE"

#################### End Celery settings ##############################


#################### Log info to console for debugging ##############################

print("=" * 80)
print("CodePost Configuration:")
print(f"CodePost API running on {API_URL}")
print(f"CodePost Client running on {CLIENT_URL}")
print(f"CodePost API running in {'debug' if DEBUG else 'production'} mode")
print(f"CodePost API Admins are {', '.join([f'{name} <{email}>' for name, email in ADMINS])}")
print("=" * 80)
print("Celery Configuration:")
print(f"  Broker URL: {CELERY_BROKER_URL}")
print(f"  Default Queue: {CELERY_DEFAULT_QUEUE}")
print(f"  Result Backend: {CELERY_RESULT_BACKEND}")
print(f"  Autograder Auto Execute: {AUTOGRADER_AUTO_EXECUTE}")
print("=" * 80)
print("Database Configuration:")
print(f"  Database Engine: {DATABASES['default']['ENGINE']}")
print(f"  Database Name: {DATABASES['default']['NAME']}")
print(f"  Database Host: {DATABASES['default'].get('HOST', 'N/A')}")
print(f"  Database Port: {DATABASES['default'].get('PORT', 'N/A')}")
print(f"  Database User: {DATABASES['default'].get('USER', 'N/A')}")
print("=" * 80)
print("EMAIL Configuration:")
print(f"  EMAIL_HOST: {EMAIL_HOST}")
print(f"  EMAIL_PORT: {EMAIL_PORT}")
print(f"  TLS: {EMAIL_USE_TLS} SSL: {EMAIL_USE_SSL}")
print(f"  DEFAULT_EMAIL_FROM: {DEFAULT_EMAIL_FROM}")
if OVERRIDE_EMAIL:
    print(f"  OVERRIDE_EMAIL: {OVERRIDE_EMAIL}")
print("=" * 80)



print("=" * 80)
print("API Documentation info:")
print(f"API Documentation URL: {API_URL}/api/schema/")
print(f"API Documentation YAML: {API_URL}/api/schema/yaml/")
print("=" * 80)

print("""
Django settings loaded successfully.


 ██████╗ ██████╗ ██████╗ ███████╗██████╗  ██████╗ ███████╗████████╗
██╔════╝██╔═══██╗██╔══██╗██╔════╝██╔══██╗██╔═══██╗██╔════╝╚══██╔══╝
██║     ██║   ██║██║  ██║█████╗  ██████╔╝██║   ██║███████╗   ██║   
██║     ██║   ██║██║  ██║██╔══╝  ██╔═══╝ ██║   ██║╚════██║   ██║   
╚██████╗╚██████╔╝██████╔╝███████╗██║     ╚██████╔╝███████║   ██║   
 ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝      ╚═════╝ ╚══════╝   ╚═╝   

Welcome to CodePost!      
      """)
print("=" * 80)
