# Generated by Django 5.2.4 on 2025-07-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='Event')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(null=True)),
                ('last_triggered_status', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
