# Generated by Django 2.1.5 on 2020-05-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0077_auto_20200503_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='Event')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(null=True)),
                ('last_triggered_status', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
