[pytest]
DJANGO_SETTINGS_MODULE = codepost.settings
python_files = tests.py test_*.py *_tests.py
strict_markers = true
addopts =
    -ra
    --strict-markers
    -n auto
    --ignore=sdk_output
    --ignore=sdk_test_output
    --ignore=examples
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks integration tests requiring external services
filterwarnings =
    ignore::DeprecationWarning:coreapi
    ignore::DeprecationWarning:factory
