services:
  - type: web
    name: api
    region: ohio
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn --workers=4 --threads=16  codepost.wsgi:application'
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: worker
    name: worker
    region: ohio
    env: python
    buildCommand: './build.sh'
    startCommand: 'celery --app autograder worker --loglevel info --concurrency 4 --task-events'
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: flower
    region: ohio
    plan: starter
    env: python
    buildCommand: 'poetry install'
    startCommand: 'celery --app autograder flower --basic-auth=richard:fruitabega'
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
