# Generated by Django 2.1.2 on 2019-02-18 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the assignment.', max_length=32)),
                ('isReleased', models.BooleanField(default=False, help_text="A boolean field. 'True' if the assignment is released for students to view. 'False' otherwise.")),
                ('points', models.PositiveIntegerField(help_text='Total points for the assignment.', validators=[django.core.validators.MinValueValidator(0)])),
                ('mean', models.DecimalField(blank=True, decimal_places=2, help_text='The average grade of the assignment. Null if no submissions yet', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('median', models.DecimalField(blank=True, decimal_places=2, help_text='The median grade of the assignment. Null if no submissions yet', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='The text on the comment')),
                ('pointDelta', models.DecimalField(blank=True, decimal_places=2, help_text='The points deducted. A negative number represents a bonus.', max_digits=5, null=True)),
                ('startChar', models.IntegerField(help_text='An integer representing the character position a comment begins on.')),
                ('endChar', models.IntegerField(help_text='An integer representing the character position a comment ends on.')),
                ('startLine', models.IntegerField(help_text='An integer representing the line number a comment begins on.')),
                ('endLine', models.IntegerField(help_text='An integer representing the line number a comment begins on.')),
                ('author', models.ForeignKey(help_text='The username of the author of the comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the course.', max_length=16)),
                ('period', models.CharField(help_text='A string describing the period (e.g. F2019, T32019, etc.', max_length=32)),
                ('sendReleasedSubmissionsToBack', models.BooleanField(default=False, help_text='A boolean field. If True, submissions that are claimed and subsequently released will be added to the back of the grading queue.')),
                ('showStudentsStatistics', models.BooleanField(default=False, help_text='A boolean field. If True, students will be able to view basic grade statistics for released assignments.')),
                ('timezone', models.CharField(default='US/Eastern', help_text='Timezone in which course operates.', max_length=32)),
                ('emailNewUsers', models.BooleanField(default=False, help_text='A boolean field. If True, when emails are added to a course roster that do not correspond to existing codePost users, those emails will be sent an email notifying that they have been added to a course and providing a link to register their (new) accounts.')),
                ('courseAdmins', models.ManyToManyField(help_text='A list of usernames for admins for the course.', related_name='courseAdmin_courses', to=settings.AUTH_USER_MODEL)),
                ('graders', models.ManyToManyField(help_text='A list of usernames of graders for the course.', related_name='grader_courses', to=settings.AUTH_USER_MODEL)),
                ('inactive_courseAdmins', models.ManyToManyField(help_text='A list of usernames of admins inactive in the course.', related_name='courseAdmin_inactive_courses', to=settings.AUTH_USER_MODEL)),
                ('inactive_graders', models.ManyToManyField(help_text='A list of usernames of graders inactive in the course.', related_name='grader_inactive_courses', to=settings.AUTH_USER_MODEL)),
                ('inactive_students', models.ManyToManyField(help_text='A list of usernames of students unenrolled in the course.', related_name='student_inactive_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the file.', max_length=32)),
                ('code', models.TextField(help_text='The code in a file.')),
                ('extension', models.CharField(help_text="The extension for the file (e.g. '.java' or '.py'", max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the organization.', max_length=64, unique=True)),
                ('shortname', models.CharField(help_text='A shortname for the organization (e.g. Princeton University -> PU)', max_length=12, unique=True)),
                ('emailDomain', models.CharField(help_text='Regular expression describing standard email domains for the organization (e.g. *@princeton.edu)', max_length=128, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canCreateCourses', models.BooleanField(default=False)),
                ('canModifyRosters', models.BooleanField(default=False)),
                ('pendingValidation', models.BooleanField(default=False)),
                ('api_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.Token')),
                ('organization', models.ForeignKey(blank=True, help_text='The related organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.Organization')),
                ('user', models.OneToOneField(help_text='The username of the related user.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the category (e.g. 'General').", max_length=32)),
                ('pointLimit', models.PositiveIntegerField(blank=True, help_text='An integer cap for the maximum number of points that can be deducted under this category.', null=True)),
                ('assignment', models.ForeignKey(help_text='The related assignment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='rubricCategories', to='core.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='The text on the rubric comment.', max_length=500)),
                ('pointDelta', models.DecimalField(decimal_places=2, help_text='The points deducted. A negative number represents a bonus.', max_digits=5)),
                ('category', models.ForeignKey(help_text='The related rubricCategory_id', on_delete=django.db.models.deletion.CASCADE, related_name='rubricComments', to='core.RubricCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the section.', max_length=16)),
                ('course', models.ForeignKey(help_text='The related course_id.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.Course')),
                ('leaders', models.ManyToManyField(blank=True, help_text='A list of usernames of graders leading the section.', related_name='leader_sections', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(help_text='A list of usernames of students in the section.', related_name='student_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinalized', models.BooleanField(default=False, help_text="A boolean field. 'True' if the submission is finalized. 'False' otherwise.")),
                ('dateEdited', models.DateTimeField(default=django.utils.timezone.now, help_text='The date this submission (or any of its associated files or comments) was last edited.')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='The grade for the submission. Null if not graded yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('queueOrderKey', models.IntegerField(default=0, help_text='Index used to order the queue from which graders draw submissions. Will sort low to high.')),
                ('gradeFrozen', models.BooleanField(default=False, help_text="A boolean field. If 'True', the submissions grade will not be re-calculated based on the current comments applied to it. Warning: this can cause grade to become out of sync with the submission's comments.")),
                ('assignment', models.ForeignKey(help_text='The related assignment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.Assignment')),
                ('grader', models.ForeignKey(blank=True, help_text='The username of the assigned grader for the submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grader_submissions', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(help_text='A list of usernames of students for the submission.', related_name='student_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='submission',
            field=models.ForeignKey(help_text='The related submission_id.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Submission'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(help_text='The related organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(help_text='A list of usernames of students enrolled in the course.', related_name='student_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='superGraders',
            field=models.ManyToManyField(help_text='A list of usernames of graders for the course who have expanded permissions.', related_name='superGrader_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(help_text='The related file_id.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.File'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rubricComment',
            field=models.ForeignKey(blank=True, help_text='The related rubricComment_id. Null if no rubric comment linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.RubricComment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(help_text='The related course_id.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='rubriccomment',
            unique_together={('text', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='rubriccategory',
            unique_together={('name', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'submission')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'period', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'course')},
        ),
    ]
