# Generated by Django 2.1.2 on 2019-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sortKey',
            field=models.IntegerField(default=0, help_text="Optional integer to specify the order of a Course's Assignments."),
        ),
    ]
