# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-07-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_submissionhistory_options_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('sortKey', 'name')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', 'period')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('name',)},
        ),
    ]
