# Generated by Django 5.2.4 on 2025-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assignment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('queueOrderKey', 'dateUploaded')},
        ),
    ]
