# Generated by Django 2.1.2 on 2019-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190327_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hideGrades',
            field=models.BooleanField(default=False, help_text="A boolean field. 'True' if the students should not see their grades for this assignment. 'False' otherwise."),
        ),
    ]
