# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-07-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissiontest',
            options={'ordering': ('created',)},
        ),
    ]
