# Generated by Django 2.1.2 on 2019-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_hidegrades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The name of the course.', max_length=36),
        ),
    ]
