# Generated by Django 2.1.2 on 2019-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190407_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccategory',
            name='sortKey',
            field=models.IntegerField(default=0, help_text="Optional integer to specify the order of an Assignment's Rubric Categories"),
        ),
    ]
