# Generated by Django 5.2.4 on 2025-08-08 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_submissiontest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPasswordSet',
            field=models.BooleanField(default=False, help_text='A boolean field. If True, the user has set a password for their account. If False, the user has not set a password and should be prompted to do so.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='inactive_courseAdmins',
            field=models.ManyToManyField(blank=True, default=list, help_text='A list of usernames of admins inactive in the course.', related_name='courseAdmin_inactive_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='inactive_graders',
            field=models.ManyToManyField(blank=True, default=list, help_text='A list of usernames of graders inactive in the course.', related_name='grader_inactive_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='inactive_students',
            field=models.ManyToManyField(blank=True, default=list, help_text='A list of usernames of students unenrolled in the course.', related_name='student_inactive_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
