# Generated by Django 2.1.2 on 2019-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rubriccategory_sortkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccomment',
            name='sortKey',
            field=models.IntegerField(default=0, help_text="Optional integer to specify the order of a Rubric Category's comments."),
        ),
    ]
