# Generated manually to handle File -> SubmissionFile/AssignmentFile/CourseFile migration
# This migration assumes starting from a clean 0006 state (production)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_profile_ispasswordset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Rename 'code' field to 'data' on File model
        migrations.RenameField(
            model_name="file",
            old_name="code",
            new_name="data",
        ),
        
        # Step 2: Alter File model fields for clarity
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(help_text="The name of the file.", max_length=250),
        ),
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.TextField(
                help_text="The data in a file. should be utf-8 encoded text.",
                default="",
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Optional file path, delimited by slashes, to indicate a directory structure.",
                max_length=500,
                null=True,
            ),
        ),
        
        # Step 3: Create SubmissionFile child model
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.file",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The related submission_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.submission",
                    ),
                ),
                (
                    "hiddenBeforePublish",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this file should hidden to students before their feedback has been published. This is for autogenerated test files that shouldn't be exposed to students on upload.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.file",),
        ),
        
        # Step 4: Create AssignmentFile child model
        migrations.CreateModel(
            name="AssignmentFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.file",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The related assignment_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.assignment",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this file is required for submission.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Description of the file template.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.file",),
        ),
        
        # Step 5: Create CourseFile child model
        migrations.CreateModel(
            name="CourseFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.file",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.file",),
        ),
        
        # Step 6: Remove old fields from File model
        migrations.RemoveField(
            model_name="file",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="file",
            name="hiddenBeforePublish",
        ),
        
        # Step 7: Update other model fields (from original migration)
        migrations.AlterField(
            model_name="assignment",
            name="uploadDueDate",
            field=models.DateTimeField(
                help_text="The date after which students are not allowed to upload submissions. Only useful if allowStudentUpload is set to True.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="inactive_courseAdmins",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of usernames of admins inactive in the course.",
                related_name="courseAdmin_inactive_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="inactive_graders",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of usernames of graders inactive in the course.",
                related_name="grader_inactive_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="inactive_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of usernames of students unenrolled in the course.",
                related_name="student_inactive_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
