# Generated by Django 5.2.4 on 2025-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_migrate_files_to_submission_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filetemplate",
            name="assignment",
        ),
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.TextField(
                default="",
                help_text="The data in a file. should be utf-8 encoded text.",
            ),
        ),
    ]
