# Generated by Django 2.1.2 on 2019-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rubriccomment_sortkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anonymousGrading',
            field=models.BooleanField(default=False, help_text="A boolean field. If 'True', graders will not have access to the students field of submission objects, unless they have elevated privileges."),
        ),
        migrations.AddField(
            model_name='course',
            name='anonymousGradingDefault',
            field=models.BooleanField(default=False, help_text='A boolean field. If True, new assignments will have anonymous grading mode enabled by default.'),
        ),
    ]
