# Generated by Django 5.2.4 on 2025-10-09 17:12

from django.db import migrations, models


def safe_remove_filetemplate_assignment(apps, schema_editor):
    """Safely remove assignment field from FileTemplate if it exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if FileTemplate table exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'core_filetemplate'
        """)
        
        if cursor.fetchone()[0] == 0:
            print("✓ FileTemplate table doesn't exist, skipping")
            return
        
        # Check if assignment_id column exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'core_filetemplate'
            AND COLUMN_NAME = 'assignment_id'
        """)
        
        if cursor.fetchone()[0] > 0:
            # Drop foreign key constraint first
            cursor.execute("""
                SELECT CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'core_filetemplate'
                AND COLUMN_NAME = 'assignment_id'
                AND REFERENCED_TABLE_NAME IS NOT NULL
            """)
            fk_result = cursor.fetchone()
            if fk_result:
                fk_name = fk_result[0]
                print(f"→ Dropping foreign key {fk_name} from FileTemplate")
                cursor.execute(f"ALTER TABLE core_filetemplate DROP FOREIGN KEY {fk_name}")
            
            print("→ Dropping assignment_id from FileTemplate")
            cursor.execute("ALTER TABLE core_filetemplate DROP COLUMN assignment_id")
        else:
            print("✓ assignment_id already removed from FileTemplate")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_migrate_files_to_submission_files"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_filetemplate_assignment,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.TextField(
                default="",
                help_text="The data in a file. should be utf-8 encoded text.",
            ),
        ),
    ]
