# Generated by Django 5.2.4 on 2025-10-09 17:12
# PATCHED for SQLite compatibility (tests)

from django.db import migrations, models

def column_exists(cursor, table, column, vendor):
    if vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info({table})")
        columns = [row[1] for row in cursor.fetchall()]
        return column in columns
    else:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = %s
            AND COLUMN_NAME = %s
        """, [table, column])
        return cursor.fetchone()[0] > 0

def table_exists(cursor, table, vendor):
    if vendor == 'sqlite':
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=%s", [table])
        return cursor.fetchone() is not None
    else:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = %s
        """, [table])
        return cursor.fetchone()[0] > 0

def drop_sqlite_indexes(cursor, table, column):
    try:
        cursor.execute(f"PRAGMA index_list({table})")
        indexes = cursor.fetchall()
        for idx in indexes:
            index_name = idx[1]
            cursor.execute(f"PRAGMA index_info({index_name})")
            cols = cursor.fetchall()
            for c in cols:
                if c[2] == column:
                    print(f"→ Dropping SQLite index {index_name} on {column}")
                    cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
                    break
    except Exception as e:
        print(f"Warning: Failed to enumerate/drop indexes for {table}.{column}: {e}")

def safe_remove_filetemplate_assignment(apps, schema_editor):
    """Safely remove assignment field from FileTemplate if it exists"""
    with schema_editor.connection.cursor() as cursor:
        vendor = schema_editor.connection.vendor
        
        # Check if FileTemplate table exists
        if not table_exists(cursor, 'core_filetemplate', vendor):
            print("✓ FileTemplate table doesn't exist, skipping")
            return
        
        # Check if assignment_id column exists
        if column_exists(cursor, 'core_filetemplate', 'assignment_id', vendor):
            if vendor != 'sqlite':
                # Drop foreign key constraint first
                cursor.execute("""
                    SELECT CONSTRAINT_NAME
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'core_filetemplate'
                    AND COLUMN_NAME = 'assignment_id'
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                """)
                fk_result = cursor.fetchone()
                if fk_result:
                    fk_name = fk_result[0]
                    print(f"→ Dropping foreign key {fk_name} from FileTemplate")
                    cursor.execute(f"ALTER TABLE core_filetemplate DROP FOREIGN KEY {fk_name}")
            else:
                drop_sqlite_indexes(cursor, 'core_filetemplate', 'assignment_id')
            
            print("→ Dropping assignment_id from FileTemplate")
            cursor.execute("ALTER TABLE core_filetemplate DROP COLUMN assignment_id")
        else:
            print("✓ assignment_id already removed from FileTemplate")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_migrate_files_to_submission_files"),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_filetemplate_assignment,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.TextField(
                default="",
                help_text="The data in a file. should be utf-8 encoded text.",
            ),
        ),
    ]
