# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-10-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_filetemplate_assignment_alter_file_data"),
    ]

    operations = [
        # Note: FileTemplate field removals and AssignmentFile field additions
        # This migration only updates the Comment.file foreign key
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.ForeignKey(
                help_text="The related file_id.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.submissionfile",
            ),
        ),
    ]
