# Generated by Django 5.2.4 on 2025-10-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_filetemplate_assignment_alter_file_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filetemplate",
            name="code",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="name",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="path",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="required",
        ),
        migrations.AddField(
            model_name="assignmentfile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description shown to students."
            ),
        ),
        migrations.AddField(
            model_name="assignmentfile",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="If student upload is enabled, a file with this name and extension will be required.",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.ForeignKey(
                help_text="The related file_id.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.submissionfile",
            ),
        ),
    ]
