# Generated by Django 2.1.2 on 2019-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190426_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowGradersToEditRubric',
            field=models.BooleanField(default=False, help_text='A boolean field. If True, graders will be allowed to add and update unlinked rubric comments.'),
        ),
    ]
