# Generated by Django 2.1.2 on 2019-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_allowgraderstoeditrubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccategory',
            name='helpText',
            field=models.TextField(blank=True, help_text='Subtext for the category name.'),
        ),
    ]
