# Generated by Django 2.1.2 on 2019-05-05 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rubriccategory_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasViewed', models.BooleanField(default=False, help_text='A boolean field indicating whether the student has seen the submission.')),
                ('dateViewed', models.DateTimeField(blank=True, help_text='The date this submission (or any of its associated files or comments) was last edited.', null=True)),
                ('student', models.ForeignKey(help_text='Username of student for the submissionHistory', on_delete=django.db.models.deletion.CASCADE, related_name='student_submissionHistories', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='The related submission_id.', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.Submission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submissionhistory',
            unique_together={('submission', 'student')},
        ),
    ]
