# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-10-13 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_assignmentdataset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentdataset",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="assignmentdataset",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="assignmentdataset",
            name="file_size",
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="assignment",
            field=models.ForeignKey(
                help_text="The related assignment_id.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataSets",
                to="core.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the data set."
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="file",
            field=models.FileField(
                help_text="The data set file", upload_to="assignment_datasets/"
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If True, this dataset will be mounted during code execution.",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="mount_path",
            field=models.CharField(
                blank=True,
                help_text="Path where dataset will be mounted in execution environment (e.g., 'shared/mnist'). Defaults to 'shared/<name>'.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentdataset",
            name="name",
            field=models.CharField(
                help_text="The name of the data set.", max_length=64
            ),
        ),
    ]
