# Generated by Django 2.1.2 on 2019-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submissionHistory_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showProductTips',
            field=models.BooleanField(default=True),
        ),
    ]
