# Generated by Django 2.1.2 on 2019-07-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_showproducttips'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rubriccategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rubriccomment',
            unique_together=set(),
        ),
    ]
