# Generated by Django 5.2.4 on 2025-10-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cached_execution_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="dateUploaded",
            field=models.DateTimeField(
                default=None,
                help_text="The date this submission was created. None if just created, and files haven't been uploaded yet. Used for Celery tasks.",
            ),
        ),
    ]
