# Generated by Django 2.1.2 on 2019-07-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rubric_nameconstraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='emailDomain',
        ),
    ]
