# Generated by Django 2.1.2 on 2019-08-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_organization_emaildomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.IntegerField(default=0, help_text='An integer representing the feedback applied to this comment. Currently only valid if rubricComment is not null.'),
        ),
    ]
