# Generated by Django 5.2.4 on 2025-10-29 03:24

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def safe_remove_filetemplate_fields(apps, schema_editor):
    """
    Safely remove fields from filetemplate table if they exist.
    This handles cases where the table structure may have already been modified.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'core_filetemplate'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            return  # Table doesn't exist, nothing to do
        
        # List of columns to remove
        columns_to_remove = ['assignment_id', 'code', 'description', 'extension', 'name', 'path', 'required']
        
        for column in columns_to_remove:
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.columns 
                WHERE table_schema = DATABASE()
                AND table_name = 'core_filetemplate'
                AND column_name = %s
            """, [column])
            
            column_exists = cursor.fetchone()[0] > 0
            
            if column_exists:
                # Remove the column
                cursor.execute(f"ALTER TABLE core_filetemplate DROP COLUMN {column}")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_submission_dateuploaded"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(safe_remove_filetemplate_fields, reverse_code=migrations.RunPython.noop),
        # Update Django's migration state to reflect the removed fields
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="assignment",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="code",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="description",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="extension",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="name",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="path",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="required",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description shown to students."
            ),
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="If student upload is enabled, a file with this name and extension will be required.",
            ),
        ),
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="The one-time token string.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=core.models.get_default_token_expiry),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether the token has been used."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The username of the related user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
