# Generated by Django 5.2.4 on 2025-10-29 03:24

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_submission_dateuploaded"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filetemplate",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="code",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="name",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="path",
        ),
        migrations.RemoveField(
            model_name="filetemplate",
            name="required",
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description shown to students."
            ),
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="If student upload is enabled, a file with this name and extension will be required.",
            ),
        ),
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="The one-time token string.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=core.models.get_default_token_expiry),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether the token has been used."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The username of the related user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
