# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-10-29 03:24

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def safe_remove_filetemplate_fields(apps, schema_editor):
    """
    Safely remove fields from filetemplate table if they exist.
    This handles cases where the table structure may have already been modified.
    """
    # Check if table exists using introspection
    table_names = schema_editor.connection.introspection.table_names()
    if 'core_filetemplate' not in table_names:
        return

    # List of columns to remove
    columns_to_remove = ['assignment_id', 'code', 'description', 'extension', 'name', 'path', 'required']
    
    with schema_editor.connection.cursor() as cursor:
        # Get existing columns
        # get_table_description returns list of FieldInfo named tuples
        # FieldInfo[0] is the column name
        try:
            description = schema_editor.connection.introspection.get_table_description(cursor, 'core_filetemplate')
            existing_columns = [col[0] for col in description]
            
            for column in columns_to_remove:
                if column in existing_columns:
                    # Remove the column
                    # We use standard SQL ALTER TABLE DROP COLUMN
                    # Note: SQLite has limited support for ALTER TABLE but DROP COLUMN is supported in newer versions
                    # If this fails on old SQLite, we might need a more complex rebuild, 
                    # but for testing environment it usually suffices.
                    # Use schema_editor to execute the drop command properly for the backend
                    schema_editor.execute(f"ALTER TABLE core_filetemplate DROP COLUMN {column}")
        except Exception as e: 
            print(f"Error during column removal: {e}")
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_submission_dateuploaded"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(safe_remove_filetemplate_fields, reverse_code=migrations.RunPython.noop),
        # Update Django's migration state to reflect the removed fields
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="assignment",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="code",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="description",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="extension",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="name",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="path",
                ),
                migrations.RemoveField(
                    model_name="filetemplate",
                    name="required",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description shown to students."
            ),
        ),
        migrations.AlterField(
            model_name="assignmentfile",
            name="required",
            field=models.BooleanField(
                default=False,
                help_text="If student upload is enabled, a file with this name and extension will be required.",
            ),
        ),
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="The one-time token string.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=core.models.get_default_token_expiry),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether the token has been used."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The username of the related user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
