# Generated by Django 2.1.2 on 2019-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='commentFeedback',
            field=models.BooleanField(default=True, help_text='A boolean field. If True, students can provide feedback on rubric comments.'),
        ),
    ]
