# Generated by Django 5.2.4 on 2025-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_submission_dateuploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="maxLateDays",
            field=models.IntegerField(
                default=2,
                help_text="An integer representing the maximum number of late days to continue to accept submissions for this assignment.",
            ),
        ),
    ]
