# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-12-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_assignment_maxlatedays"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="studentsCanSeeGraders",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="If set, overrides course setting. If True, students can see graders for this assignment.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="studentsCanSeeGraders",
            field=models.BooleanField(
                default=False,
                help_text="If True, students can see the grader who graded their submission.",
            ),
        ),
    ]
