# Generated by Django 2.1.2 on 2019-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rubriccategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccategory',
            name='name',
            field=models.CharField(help_text="The name of the category (e.g. 'General').", max_length=72),
        ),
    ]
