# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_studentsCanSeeGraders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solutionfile",
            name="environment",
        ),
        migrations.AddField(
            model_name="environment",
            name="build_logs",
            field=models.TextField(
                blank=True, default="", help_text="Logs from the image build process."
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="build_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Built"),
                    (1, "Building"),
                    (2, "Success"),
                    (3, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="image_name",
            field=models.CharField(
                blank=True,
                help_text="The Docker image name for this environment.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="last_built",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last build.", null=True
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="requirements",
            field=models.TextField(
                blank=True, default="", help_text="Python requirements.txt content."
            ),
        ),
        migrations.DeleteModel(
            name="HelperFile",
        ),
        migrations.DeleteModel(
            name="SolutionFile",
        ),
    ]
