# Generated by Django 2.1.2 on 2019-08-27 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rubriccategory_name_72'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowStudentUpload',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, students will be allowed to upload submissions until the upload due date.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='liveFeedbackMode',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, students can see their submission and comments before finalization and published'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='uploadDueDate',
            field=models.DateTimeField(help_text='The date after which students are not allowed to upload submissions. Only useful if allowStudentUplaod is set to True.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='dateUploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date this submission was created.'),
        ),
    ]
