# Generated by Django 5.2.4 on 2025-12-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_solutionfile_environment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="dumpMode",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="exposeDumpLogs",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="isRunning",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="testParsing",
        ),
        migrations.DeleteModel(
            name="SourceFile",
        ),
    ]
