# Generated by Django 2.1.2 on 2019-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190903_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='additiveGrading',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, grades begin at 0 (instead of assignment.points)'),
        ),
        migrations.AlterField(
            model_name='rubriccategory',
            name='pointLimit',
            field=models.IntegerField(blank=True, help_text='An integer cap for the maximum number of points that can be deducted under this category.', null=True),
        ),
    ]
