# Generated by Django 2.1.2 on 2019-09-06 22:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190904_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.CharField(blank=True, help_text='The color in which the comment will render in codePost.', max_length=7, validators=[core.validators.validate_hex_color]),
        ),
    ]
