# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-14 05:20

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_environment_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="env_vars",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="Dictionary of environment variables to set in the Docker container.",
            ),
        ),
    ]
