# Generated by Django 2.1.2 on 2019-09-07 05:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_comment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(blank=True, help_text='The color in which the comment will render in codePost.', max_length=7, null=True, validators=[core.validators.validate_hex_color]),
        ),
    ]
