# Generated by Django 2.1.2 on 2019-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190907_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hideGradersFromStudents',
            field=models.BooleanField(default=True, help_text='A boolean field. If True, the graders of a submission will be hidden from students.'),
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(help_text='Optional file path, delimited by slashes, to indicate a directory structure in submission.', max_length=500, null=True),
        ),
    ]
