# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-14 14:32

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_environment_env_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="convergence_stats",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="Tracks module error counts: {module_name: occurrence_count}",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="successful_runs",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Count of successful submission runs (for stability check)",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="total_runs",
            field=models.PositiveIntegerField(
                default=0, help_text="Total submission runs"
            ),
        ),
    ]
