# Generated by Django 5.2.4 on 2025-12-14 15:48

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_convergence_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="convergence_failed_notified",
            field=models.BooleanField(
                default=False,
                help_text="True if admin was notified of convergence failure",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="convergence_pending",
            field=models.BooleanField(
                default=False,
                help_text="True if waiting to validate convergence after auto-update",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="current_build_version",
            field=models.PositiveIntegerField(
                default=1, help_text="Current image version number"
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="image_history",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=list,
                help_text="List of {version, image_name, requirements, built_at, status}",
            ),
        ),
    ]
