# Generated by Django 5.2.4 on 2025-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_image_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date when the course will be automatically deleted.",
                null=True,
            ),
        ),
    ]
