# Generated by Django 2.1.2 on 2019-09-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190908_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, help_text='Optional file path, delimited by slashes, to indicate a directory structure in submission.', max_length=500, null=True),
        ),
    ]
