# Generated by Django 2.1.2 on 2019-09-09 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20190908_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowRegradeRequests',
            field=models.BooleanField(default=False, help_text='A boolean field. If True, students will be allowed to submit questions and regrade requests after their submission has been graded.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='regradeDeadline',
            field=models.DateTimeField(help_text='The date after which students are not allowed submit a regrade request.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionDate',
            field=models.DateTimeField(blank=True, help_text='The date the request / question was submitted.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionIsOpen',
            field=models.BooleanField(default=False, help_text='A boolean field. If true the submission has an open question.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionIsRegrade',
            field=models.BooleanField(default=False, help_text="A boolean field. If 'True', the submission's question is a regrade request."),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionResponder',
            field=models.ForeignKey(blank=True, help_text='The username of the responder for the question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grader_regraded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionResponse',
            field=models.CharField(blank=True, help_text='The text of the question response.', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionText',
            field=models.CharField(blank=True, help_text='The text of the question.', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='responseDate',
            field=models.DateTimeField(blank=True, help_text='The date the response was submitted.', null=True),
        ),
    ]
