# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-12-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_course_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email_domain",
            field=models.CharField(
                blank=True,
                help_text="The email domain associated with the organization.",
                max_length=64,
                null=True,
            ),
        ),
    ]
