# Generated by Django 2.1.2 on 2019-09-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_assignment_submissions_regrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='forcedRubricMode',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, graders will be required to link a rubric comment on all comments.'),
        ),
    ]
