# Generated by Django 2.1.2 on 2019-09-18 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_assignment_forcedrubricmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='The name of the template file.', max_length=48)),
                ('code', models.TextField(help_text='The code in a file.')),
                ('extension', models.CharField(help_text="The extension for the file (e.g. '.java' or '.py'", max_length=8)),
                ('path', models.CharField(blank=True, help_text='Optional file path, delimited by slashes, to indicate a directory structure in submission.', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='templateMode',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, admins will be able upload template code files. Those template files will be used to de-emphasize provided versus student-written code in submissions.'),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='assignment',
            field=models.ForeignKey(help_text='The related assignment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='fileTemplates', to='core.Assignment'),
        ),
    ]
