# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_environment_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="hash",
            field=models.CharField(
                default="", help_text="The SHA-256 hash of the file.", max_length=256
            ),
        ),
    ]
