# Generated by Django 2.1.2 on 2019-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190918_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='collaborativeRubricMode',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, admins and graders can edit the assignment rubric inline in the code console.'),
        ),
    ]
