# Generated by Django 5.2.4 on 2025-12-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="expectPlot",
            field=models.BooleanField(
                default=False,
                help_text="If True, the test will only pass if a plot is generated.",
            ),
        ),
    ]
