# Generated by Django 5.2.4 on 2025-12-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_testcase_dataset_testcase_expectplot"),
        ("core", "0030_testcase_expectplot"),
    ]

    operations = []
