# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-12-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_testcase_dataset_testcase_expectplot"),
    ]

    operations = []
