# Generated by Django 2.1.2 on 2019-09-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_assignment_collaborativerubricmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(help_text="The extension for the file (e.g. '.java' or '.py'", max_length=36),
        ),
        migrations.AlterField(
            model_name='filetemplate',
            name='extension',
            field=models.CharField(help_text="The extension for the file (e.g. '.java' or '.py'", max_length=36),
        ),
    ]
