# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_merge_20251218_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="targetCellId",
            field=models.CharField(
                blank=True,
                help_text="The ID of the notebook cell to target for execution.",
                max_length=64,
                null=True,
            ),
        ),
    ]
