# Generated by Django 2.1.2 on 2019-10-17 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190920_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.DecimalField(decimal_places=2, help_text='Total points for the assignment.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
