# Generated by Django 2.1.2 on 2019-11-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191017_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccomment',
            name='explanation',
            field=models.TextField(blank=True, help_text='The explanation of a rubric comment shown to students.'),
        ),
    ]
