# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_testcase_targetcellid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentdataset",
            name="mount_path",
            field=models.CharField(
                blank=True,
                help_text="Path where dataset will be mounted in execution environment. Can be an absolute path (e.g. '/etc/config.json') or a relative path (e.g. 'mnist'). Relative paths are mounted under '/shared'.",
                max_length=256,
            ),
        ),
    ]
