# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2025-12-30 16:15

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_assignmentdataset_mount_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="send_welcome_email",
            field=models.BooleanField(
                default=True,
                help_text="If False, suppresses welcome/added-to-course emails for users in this organization.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sso_config",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="JSON configuration for the SSO provider.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sso_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, new users in this organization are automatically activated and assume external authentication.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sso_provider",
            field=models.CharField(
                blank=True,
                help_text="The SSO provider (e.g. CAS, AZURE, OIDC, GOOGLE).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="isOrgStaff",
            field=models.BooleanField(
                default=False,
                help_text="If True, user can manage Organization settings (SSO, Defaults).",
            ),
        ),
    ]
