# Generated by Django 2.1.2 on 2019-11-14 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rubriccomment_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BashFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.TextField(blank=True, help_text='The code in a file.')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencies', models.TextField(default='[]', help_text='Dependencies of assignment environment')),
                ('language', models.CharField(choices=[('python-3.7', 'python-3.7'), ('python-2.7', 'python-2.7'), ('java', 'java'), ('c/c++', 'c/c++')], max_length=25, null=True)),
                ('compileText', models.TextField(blank=True, default='', help_text='Command to be run on every submission before tests')),
                ('isRunning', models.BooleanField(default=False, help_text='A boolean field indicating whether the environment currently is running all submissions with all tests.')),
                ('assignment', models.OneToOneField(help_text='The related assignment__id.', on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='core.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='HelperFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='The name of the template file.', max_length=48)),
                ('code', models.TextField(help_text='The code in a file.')),
                ('path', models.CharField(blank=True, help_text='Optional file path, delimited by slashes, to indicate a directory structure.', max_length=500, null=True)),
                ('environment', models.ForeignKey(help_text='The related environment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='helperFiles', to='core.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='The name of the template file.', max_length=48)),
                ('code', models.TextField(help_text='The code in a file.')),
                ('path', models.CharField(blank=True, help_text='Optional file path, delimited by slashes, to indicate a directory structure.', max_length=500, null=True)),
                ('environment', models.ForeignKey(help_text='The related environment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='solutionFiles', to='core.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(help_text='The logs of a test.')),
                ('passed', models.BooleanField(help_text="A boolean field. 'True' if the submission passed this test. 'False' otherwise.", null=True)),
                ('isError', models.BooleanField(default=False, help_text="A boolean field. 'True' if the test resulted in an error. False otherwise.")),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(help_text='The related submission_id.', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortKey', models.IntegerField(default=0, help_text="Integer to specify the order of a Assignment's Tests.")),
                ('description', models.CharField(help_text='Test description.', max_length=48)),
                ('type', models.CharField(choices=[('io', 'io'), ('native-unit', 'native-unit'), ('bash-unit', 'bash-unit'), ('bash-group', 'bash-group'), ('external', 'external')], max_length=25)),
                ('pointsFail', models.DecimalField(decimal_places=2, default=0, help_text='The points assigned to a failed test.', max_digits=5)),
                ('pointsPass', models.DecimalField(decimal_places=2, default=0, help_text='The points assigned to a passed test.', max_digits=5)),
                ('text', models.TextField(blank=True, help_text='The text of the test')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('function', models.TextField(blank=True, help_text='The function name to test')),
                ('fileName', models.TextField(blank=True, help_text='The file name to test')),
                ('expectedOutput', models.TextField(blank=True, help_text='The expected output of the test')),
                ('input', models.TextField(blank=True, help_text='The input of the test')),
                ('checkReturn', models.BooleanField(default=True, help_text="A boolean field. 'True' if the output should be compared to the return of the function. False if it should be compared to std out.")),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the test.', max_length=48)),
                ('type', models.CharField(choices=[('normal', 'normal'), ('bash', 'bash'), ('external', 'external')], max_length=25)),
                ('assignment', models.ForeignKey(help_text='The related assignment__id.', on_delete=django.db.models.deletion.CASCADE, related_name='testCategories', to='core.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='testCategory',
            field=models.ForeignKey(help_text='The related testCategory__id.', on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='core.TestCategory'),
        ),
        migrations.AddField(
            model_name='submissiontest',
            name='testCase',
            field=models.ForeignKey(help_text='The related parent test id', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.TestCase'),
        ),
        migrations.AddField(
            model_name='bashfile',
            name='testCategory',
            field=models.OneToOneField(help_text='The related testCategory_id.', on_delete=django.db.models.deletion.CASCADE, related_name='bashFile', to='core.TestCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='testcategory',
            unique_together={('name', 'assignment')},
        ),
    ]
