# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_organization_send_welcome_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="gradesReleased",
            field=models.BooleanField(
                default=False,
                help_text="A boolean field. 'True' if grades/feedback are released for students to view. 'False' otherwise.",
            ),
        ),
    ]
