# Generated by Django 2.1.2 on 2019-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20191114_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('io', 'io'), ('io_cli', 'io_cli'), ('native-unit', 'native-unit'), ('bash-unit', 'bash-unit'), ('bash-group', 'bash-group'), ('external', 'external')], max_length=25),
        ),
    ]
