# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_assignment_gradesreleased"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="gradesReleased",
            new_name="submissionsReleased",
        ),
    ]
