# Generated by Django 2.1.2 on 2019-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20191115_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccomment',
            name='text',
            field=models.TextField(blank=True, help_text='The text on the rubric comment.'),
        ),
    ]
