# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_rename_gradesreleased_assignment_submissionsreleased"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="submissionsReleased",
            new_name="feedbackReleased",
        ),
    ]
