# Generated by Django 2.1.2 on 2019-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20191117_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='showFrequentlyUsedRubricComments',
            field=models.BooleanField(default=False, help_text="A boolean field. If true, an assignment's 10 most frequently used rubric comments will be shown within the code console."),
        ),
    ]
