# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_rename_submissionsreleased_assignment_feedbackreleased"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="ai_system_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="System prompt for AI comment generation. Placeholders: {assignment_name}, {file_content}, {selected_content}, {rubric_context}, {grader_draft}",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_api_key",
            field=models.TextField(
                blank=True,
                help_text="API key for AI provider (stored encrypted)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_base_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL for Ollama or custom provider",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="Model name (e.g., gemini-1.5-flash, gpt-4)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama (Self-hosted)"),
                    ("custom", "Custom Provider"),
                ],
                help_text="AI provider for comment generation",
                max_length=32,
                null=True,
            ),
        ),
    ]
