# Generated by Django 2.1.2 on 2019-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_assignment_showfrequentlyusedrubriccomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowLateUploads',
            field=models.BooleanField(default=False, help_text='A boolean field. If True and an uploadDueDate is set, students will still be able to submit after a deadline has passed.'),
        ),
    ]
