# Generated by Django 2.1.2 on 2019-11-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_assignment_allowlateuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemplate',
            name='required',
            field=models.BooleanField(default=False, help_text='If student upload is enabled, a file with this name and extension will be required.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='exposed',
            field=models.BooleanField(default=False, help_text="If True and type is not 'external', this test will be run when a student submits, and the results shown to the student"),
        ),
        migrations.AlterField(
            model_name='filetemplate',
            name='code',
            field=models.TextField(blank=True, help_text='The code in a file.'),
        ),
    ]
