# Generated by Django 5.2.4 on 2026-01-10 14:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_ai_comment_generation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="ai_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="API key for AI provider (stored encrypted)",
                null=True,
            ),
        ),
    ]
