# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-11 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_course_ai_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rubricEditors",
            field=models.ManyToManyField(
                help_text="A list of usernames of graders for the course who are allowed to edit the rubric.",
                related_name="rubricEditor_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
