# Generated by Django 2.1.2 on 2019-11-24 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20191121_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.TextField(blank=True, help_text='The code.')),
                ('name', models.CharField(help_text='The name of the Test Group file.', max_length=48)),
            ],
        ),
        migrations.RemoveField(
            model_name='bashfile',
            name='testCategory',
        ),
        migrations.RemoveField(
            model_name='testcategory',
            name='type',
        ),
        migrations.AddField(
            model_name='environment',
            name='dumpMode',
            field=models.BooleanField(default=False, help_text='A boolean field indicating whether all test outputs should be dumped to a TESTS.TXT file.'),
        ),
        migrations.AlterField(
            model_name='helperfile',
            name='code',
            field=models.TextField(blank=True, help_text='The code in a file.'),
        ),
        migrations.AlterField(
            model_name='helperfile',
            name='name',
            field=models.CharField(help_text='The name of the Helper file.', max_length=48),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='code',
            field=models.TextField(blank=True, help_text='The code in a file.'),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='name',
            field=models.CharField(help_text='The name of the Solution file.', max_length=48),
        ),
        migrations.AlterField(
            model_name='submissiontest',
            name='passed',
            field=models.BooleanField(help_text="A boolean field. 'True' if the submission passed this test. 'False' otherwise."),
        ),
        migrations.DeleteModel(
            name='BashFile',
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='environment',
            field=models.ForeignKey(help_text='The related environment_id.', on_delete=django.db.models.deletion.CASCADE, related_name='sourceFiles', to='core.Environment'),
        ),
    ]
