# Generated by Django 2.1.2 on 2019-11-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20191124_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, help_text='A description of what the test achieves'),
        ),
    ]
