# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-12 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_course_rubriceditors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.TextField(help_text="The text of the template.")),
                (
                    "isGlobal",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this template is visible to all graders in the course.",
                    ),
                ),
                (
                    "filePath",
                    models.CharField(
                        blank=True,
                        help_text="Optional file path pattern. If set, template only shows for matching files.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "pointDelta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Points delta for this template.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this template belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_templates",
                        to="core.course",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The creator of the template.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubricComment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional linked rubric comment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="core.rubriccomment",
                    ),
                ),
                (
                    "sourceComment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original comment this template was created from. Null if manually created or source was deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_templates",
                        to="core.comment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
