# Generated by Django 2.1.2 on 2019-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_testcase_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dumpMode',
            field=models.BooleanField(default=False, help_text='A boolean field indicating whether all test outputs should be dumped to a _tests.txt file.'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='language',
            field=models.CharField(choices=[('python-3.7', 'python-3.7'), ('python-2.7', 'python-2.7'), ('java', 'java'), ('c/c++', 'c/c++')], max_length=25),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('io', 'io'), ('io_cli', 'io_cli'), ('unit', 'unit'), ('shell', 'shell'), ('file', 'file'), ('external', 'external')], max_length=25),
        ),
    ]
