# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_commenttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenttemplate",
            name="cellId",
            field=models.CharField(
                blank=True,
                help_text="Optional notebook cell ID. If set, template only shows for this cell.",
                max_length=36,
                null=True,
            ),
        ),
    ]
