# Generated by Django 2.1.2 on 2019-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20191125_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Error'), (3, 'Never run')], default=3),
        ),
    ]
