# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_commenttemplate_cellid"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI comment generation is disabled even if configured",
            ),
        ),
    ]
