# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_ai_disabled_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commenttemplate",
            name="course",
        ),
        migrations.AddField(
            model_name="commenttemplate",
            name="assignment",
            field=models.ForeignKey(
                default=1,
                help_text="The assignment this template belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_templates",
                to="core.assignment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commenttemplate",
            name="isGlobal",
            field=models.BooleanField(
                default=False,
                help_text="If True, this template is visible to all graders in the assignment.",
            ),
        ),
    ]
