# Generated by Django 2.1.2 on 2019-11-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_testcase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='status',
        ),
        migrations.AddField(
            model_name='testcase',
            name='solutionStatus',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Error'), (3, 'Never run')], default=3),
        ),
    ]
