# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_change_commenttemplate_to_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="checkReturn",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="expectPlot",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="expectedOutput",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="function",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="input",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="isFlexible",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="outputIsFile",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="outputIsRegexp",
        ),
        migrations.AddField(
            model_name="testcase",
            name="rubricItem",
            field=models.ForeignKey(
                blank=True,
                help_text="The related rubric comment. If set, failure applies this rubric item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rubriccomment",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="testCode",
            field=models.TextField(
                blank=True, help_text="The custom test script code."
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="type",
            field=models.CharField(
                choices=[
                    ("io", "io"),
                    ("io_cli", "io_cli"),
                    ("unit", "unit"),
                    ("shell", "shell"),
                    ("file", "file"),
                    ("external", "external"),
                    ("script", "script"),
                ],
                max_length=25,
            ),
        ),
    ]
