# Generated by Django 2.1.2 on 2019-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20191129_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='statusOnSolution',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Error'), (3, 'Never run')], default=3),
        ),
    ]
