# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_testcase_checkreturn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontest",
            name="maxScore",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum possible score from all subtests.",
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="submissiontest",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Aggregate score earned from all subtests.",
                max_digits=7,
            ),
        ),
    ]
