# Generated by Django 2.1.2 on 2019-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20191130_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='lastSolutionRun',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Error'), (3, 'Never run')], default=3),
        ),
    ]
