# Generated by Django 2.1.2 on 2019-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20191130_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='testParsing',
            field=models.BooleanField(default=True, help_text='A boolean field indicating whether tests should be parsed from sourcefiles on save.'),
        ),
    ]
