# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_submissiontest_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="functionName",
            field=models.CharField(
                blank=True,
                help_text="The name of the function in the test script.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="maxPoints",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total points available for this category.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="testScript",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Python script containing @test decorated functions.",
            ),
        ),
    ]
