# Generated by Django 2.1.2 on 2019-12-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191206_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccategory',
            name='atMostOnce',
            field=models.BooleanField(default=False, help_text='A boolean field. If True, at most one rubric comment from this rubric category can be applied to a submission.'),
        ),
    ]
