# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_testcase_functionname_testcategory_maxpoints_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="sortKey",
            field=models.IntegerField(
                default=0, help_text="Integer to specify the order of display."
            ),
        ),
    ]
