# Generated by Django 2.1.2 on 2019-12-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('core', '0048_auto_20191207_0243'),
  ]

  operations = [
      migrations.AddField(
          model_name='profile',
          name='stripeCustomerId',
          field=models.CharField(blank=True, help_text='The customer_id from the Stripe customer object.',
                                 max_length=96, null=True, unique=True),
      ),
  ]
