# Generated by Django 2.1.2 on 2019-12-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20191209_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='dockerfile',
            field=models.TextField(blank=True, default='', help_text='The custom docker file for custom images'),
        ),
    ]
