# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_testcategory_sortkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="targetFileName",
            field=models.CharField(
                blank=True,
                help_text="The name of the file this category tests.",
                max_length=128,
                null=True,
            ),
        ),
    ]
