# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_testcategory_targetfilename"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentdataset",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="If True, this dataset will be hidden from students.",
            ),
        ),
        migrations.AddField(
            model_name="assignmentfile",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="If True, this file will be hidden from students (but available for tests/helpers).",
            ),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="helperFiles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Files to be injected into the test environment.",
                related_name="test_categories",
                to="core.assignmentfile",
            ),
        ),
        migrations.AlterField(
            model_name="testcategory",
            name="targetFileName",
            field=models.CharField(
                blank=True,
                help_text="The name of the file this test targets.",
                max_length=255,
                null=True,
            ),
        ),
    ]
