# Generated by Django 2.1.2 on 2019-12-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20191215_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='buildType',
            field=models.CharField(choices=[('default', 'default'), ('alpine', 'alpine'), ('ubuntu', 'ubuntu'), ('windows', 'windows')], default='default', max_length=25),
        ),
        migrations.AlterField(
            model_name='environment',
            name='language',
            field=models.CharField(choices=[('python-3.7', 'python-3.7'), ('python-2.7', 'python-2.7'), ('java', 'java'), ('c/c++', 'c/c++'), ('other', 'other')], default='python-3.7', max_length=25),
        ),
    ]
