# Generated by Django 5.2.4 on 2026-01-29 22:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_assignmentdataset_hidden_assignmentfile_hidden_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcategory",
            name="helperFiles",
        ),
        migrations.CreateModel(
            name="TestCategoryResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "target_path",
                    models.CharField(
                        help_text="The filename or path this resource will be saved as during test execution. Allows aliasing (e.g. use 'test1.txt' as 'input.txt').",
                        max_length=512,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The related test category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.testcategory",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The source dataset.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assignmentdataset",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="The source file.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assignmentfile",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "target_path")},
            },
        ),
    ]
