# Generated by Django 2.1.2 on 2019-12-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191221_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minComments',
            field=models.IntegerField(default=0, help_text='An integer representing the minimum number of comments that graders are asked to make prior to finalizing. 0 indicates no minimum.'),
        ),
        migrations.AddField(
            model_name='course',
            name='noUnfinalize',
            field=models.BooleanField(default=False, help_text='If True, only admins can unfinalize submissions.'),
        ),
        migrations.AddField(
            model_name='rubriccomment',
            name='instructionText',
            field=models.TextField(blank=True, help_text='Text shown to the grader in the custom text field of an instance comment.'),
        ),
        migrations.AddField(
            model_name='rubriccomment',
            name='templateTextOn',
            field=models.BooleanField(default=False, help_text='If True, instruction text will pre-populate instance comments.'),
        ),
    ]
