# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_remove_testcategory_helperfiles_testcategoryresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="timeout",
            field=models.IntegerField(
                default=30, help_text="Execution timeout in seconds for this test."
            ),
        ),
    ]
