# Generated by Django 2.1.2 on 2020-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20191227_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown to students.'),
        ),
    ]
