# Generated by Django 2.1.2 on 2020-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200102_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='allowNetworkAccess',
            field=models.BooleanField(default=False, help_text='A boolean field indicating whether tests should be run in a container that allows network access.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='outputIsFile',
            field=models.BooleanField(default=True, help_text="A boolean field. 'True' if the output is the name of a file to be compared to."),
        ),
    ]
