# Generated by Django 5.2.4 on 2026-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_remove_testcase_dataset_remove_testcase_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="questionResponse",
            field=models.TextField(
                blank=True, help_text="The text of the question response.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="questionText",
            field=models.CharField(
                blank=True,
                help_text="The text of the question.",
                max_length=500,
                null=True,
            ),
        ),
    ]
