# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-02-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_submission_questionresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentdataset",
            name="is_test_resource",
            field=models.BooleanField(
                default=False,
                help_text="If True, this dataset is used as a resource for a TestCategory.",
            ),
        ),
        migrations.AddField(
            model_name="assignmentfile",
            name="is_test_resource",
            field=models.BooleanField(
                default=False,
                help_text="If True, this file is used as a resource for a TestCategory.",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="questionResponse",
            field=models.TextField(
                blank=True, help_text="The text of the question response."
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="questionText",
            field=models.CharField(
                blank=True, help_text="The text of the question.", max_length=500
            ),
        ),
    ]
