# Generated by Django 2.1.2 on 2020-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('core', '0055_auto_20200116_0126'),
  ]

  operations = [
      migrations.AddField(
          model_name='course',
          name='archived',
          field=models.BooleanField(default=False, help_text='If True, the course will not be editable.'),
      ),
  ]
