# Generated by Django 2.1.2 on 2020-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200118_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='buildID',
            field=models.PositiveIntegerField(default=0, help_text='An integer field making each environment build distinct'),
        ),
    ]
