# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2026-02-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_assignmentdataset_is_test_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="gradersCanEditSubmissions",
            field=models.BooleanField(
                default=False,
                help_text="A boolean field. If True, graders will be allowed to edit student submissions (e.g. for testing fixes).",
            ),
        ),
    ]
