# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-02-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_assignment_graderscaneditsubmissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="runTestsOnSubmit",
            field=models.BooleanField(
                default=True,
                help_text="If True, autograder tests will automatically run when a student submits.",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="testsAffectGrade",
            field=models.BooleanField(
                default=True,
                help_text="If True, the results of autograder tests will be included in the submission grade calculation.",
            ),
        ),
    ]
