# Generated by Django 2.1.2 on 2020-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200123_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='exposeDumpLogs',
            field=models.BooleanField(default=False, help_text='If dumpMode is turned on, this boolean field determins whether the tests.txt is exposed to students on submit.'),
        ),
        migrations.AddField(
            model_name='environment',
            name='maxExposedFailedTests',
            field=models.PositiveIntegerField(help_text='An integer field indicating the limit of the number of failed tests that will be exposed to a student (nudge mode).', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='maxStudentTestRuns',
            field=models.PositiveIntegerField(help_text='An integer field indicating the max times that tests will be run if tests are exposed.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='hiddenBeforePublish',
            field=models.BooleanField(default=False, help_text="Whether this file should hidden to students before their feedback has been published. This is for autogenerated test files that shouldn't be exposed to students on upload."),
        ),
        migrations.AddField(
            model_name='submission',
            name='testRunsCompleted',
            field=models.PositiveIntegerField(default=0, help_text='Number of times exposed tests have been run for a submission. It only increments if the maxStudentTestRuns Environment setting is on.'),
        ),
    ]
