# Generated by Django 2.1.5 on 2020-02-03 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

  dependencies = [
      ('core', '0058_auto_20200124_2009'),
  ]

  operations = [
      migrations.CreateModel(
          name='CommentTag',
          fields=[
              ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('label', models.CharField(help_text='The tag label.', max_length=64, unique=True)),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.AddField(
          model_name='assignment',
          name='regradeInstructions',
          field=models.TextField(
              blank=True, default='', help_text='Instructions (in Markdown) to show students when they submit regrade requests.'),
      ),
      migrations.AddField(
          model_name='course',
          name='lateDayCreditsAllowable',
          field=models.IntegerField(
              blank=True, help_text='The number of Late Day Credits that each student gets at the beginning of the term. Null if the course does not have students submit directly to codePost.', null=True),
      ),
      migrations.AddField(
          model_name='submission',
          name='lateDayCreditsUsed',
          field=models.IntegerField(default=0, help_text='The number of Late Day Credits used by the Submission.'),
      ),
      migrations.AddField(
          model_name='comment',
          name='tags',
          field=models.ManyToManyField(help_text='A list of tags (strings) for the comment.',
                                       related_name='tag_comments', to='core.CommentTag'),
      ),
  ]
