# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
# Generated by Django 5.2.4 on 2026-02-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_assignment_runtestsonsubmit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_comments_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI comment generation is disabled even if AI is globally enabled",
            ),
        ),
    ]
