# Generated by Django 2.1.2 on 2020-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200203_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='isFlexible',
            field=models.BooleanField(default=False, help_text='Flexible mode for output checking.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='outputIsRegexp',
            field=models.BooleanField(default=False, help_text='Is expected output specified in the form of a regexp?'),
        ),
    ]
