# Generated by Django 5.2.4 on 2026-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_course_ai_comments_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Show the banner to all users when enabled.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="codePost is currently undergoing maintenance. Some features may be unavailable.",
                        help_text="The message displayed in the banner.",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0e704c",
                        help_text="Background color (CSS value, e.g. #0e704c or red).",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Banner",
                "verbose_name_plural": "Maintenance Banner",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="ai_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, all AI features are disabled even if configured",
            ),
        ),
    ]
