# Generated by Django 2.1.2 on 2020-02-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200207_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='questionResponse',
            field=models.TextField(blank=True, help_text='The text of the question response.'),
        ),
    ]
