# Generated by Django 6.0.2 on 2026-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_maintenance_banner_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="runFilesOnSubmit",
            field=models.BooleanField(
                default=True,
                help_text="If True, submission files will be automatically executed and cached when a student submits.",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancebanner",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Manually enable/disable the banner."
            ),
        ),
        migrations.AlterField(
            model_name="maintenancebanner",
            name="color",
            field=models.CharField(
                default="#0e704c",
                help_text="Background colour (any CSS value, e.g. #0e704c or red).",
                max_length=30,
            ),
        ),
    ]
