# Generated by Django 2.1.5 on 2020-02-12 14:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

  dependencies = [
      ('core', '0061_auto_20200212_0518'),
  ]

  operations = [
      migrations.AddField(
          model_name='assignment',
          name='lateDeductions',
          field=jsonfield.fields.JSONField(default=[], help_text='An array of point deductions for each day late.'),
      ),
  ]
