# Generated by Django 6.0.2 on 2026-03-04 19:11

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_assignment_runfilesonsubmit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_use_own_settings",
            field=models.BooleanField(
                default=False,
                help_text="If True, course uses its own AI settings instead of the organization's configuration",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="API key for AI provider (stored encrypted)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_base_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL for Ollama or custom provider",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_comments_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI comment generation is disabled at the organization level",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_course_policy",
            field=models.CharField(
                choices=[
                    ("all", "All courses"),
                    ("selected", "Selected courses only"),
                    ("none", "Disabled"),
                ],
                default="none",
                help_text="Controls which courses can use the organization's AI configuration: 'all', 'selected', or 'none'",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, all AI features are disabled for this organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_enabled_courses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Courses explicitly enabled for the organization's AI configuration (used when ai_course_policy is 'selected')",
                related_name="ai_enabled_by_organizations",
                to="core.course",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_model",
            field=models.CharField(
                blank=True,
                help_text="Default model name (e.g., gemini-1.5-flash, gpt-4)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama (Self-hosted)"),
                    ("custom", "Custom Provider"),
                ],
                help_text="AI provider for the organization",
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.CharField(
                        help_text="AI provider used (e.g., openai, gemini)",
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name used for this request", max_length=64
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("comment_generation", "Comment Generation"),
                            ("code_review", "Code Review"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of AI request",
                        max_length=32,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of input/prompt tokens"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of output/completion tokens"
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Total tokens (input + output)"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Estimated cost in USD for this API call",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="success",
                        help_text="Status of the request: success, error",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the request failed",
                        null=True,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment associated with this usage record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="core.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="The course associated with this usage record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="core.course",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization associated with this usage record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who triggered this AI request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["organization", "created"],
                        name="core_aiusag_organiz_7bbf0a_idx",
                    ),
                    models.Index(
                        fields=["course", "created"],
                        name="core_aiusag_course__ec980a_idx",
                    ),
                    models.Index(
                        fields=["assignment", "created"],
                        name="core_aiusag_assignm_1ed801_idx",
                    ),
                    models.Index(
                        fields=["created"], name="core_aiusag_created_fee60a_idx"
                    ),
                ],
            },
        ),
    ]
