# Generated by Django 2.1.2 on 2020-02-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200212_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='dockerDependencies',
            field=models.TextField(blank=True, default='', help_text='Dependencies of assignment environment'),
        ),
    ]
