# Generated by Django 6.0.2 on 2026-03-05 19:33

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_ai_org_settings_and_usage_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_token_rates",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Custom per-model token rates. JSON object mapping model names to {"input": <$/1M tokens>, "output": <$/1M tokens>}',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_token_rates",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Custom per-model token rates. JSON object mapping model names to {"input": <$/1M tokens>, "output": <$/1M tokens>}',
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama (Self-hosted)"),
                    ("portkey", "Portkey (Self-hosted)"),
                    ("custom", "Custom Provider"),
                ],
                help_text="AI provider for comment generation",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama (Self-hosted)"),
                    ("portkey", "Portkey (Self-hosted)"),
                    ("custom", "Custom Provider"),
                ],
                help_text="AI provider for the organization",
                max_length=32,
                null=True,
            ),
        ),
    ]
