# Generated by Django 2.1.2 on 2020-02-14 18:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200213_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='dockerDependencies',
        ),
        migrations.AddField(
            model_name='environment',
            name='dockerRunInstructions',
            field=jsonfield.fields.JSONField(default=[], help_text='Instructions to be added to the docker file with a RUN command.'),
        ),
    ]
