# Generated by Django 6.0.2 on 2026-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_ai_token_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="description",
            field=models.CharField(help_text="Test description.", max_length=255),
        ),
    ]
