# Generated by Django 2.1.2 on 2020-02-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200214_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='explanation',
            field=models.TextField(blank=True, help_text='The explanation of an assignment, visible to students.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hideFrom',
            field=models.ManyToManyField(blank=True, help_text='Sections from which to hide this assignment.', related_name='hidden_sections', to='core.Section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='isVisible',
            field=models.BooleanField(default=True, help_text="A boolean field. 'True' if the assignment is viewable by students."),
        ),
    ]
