# Generated by Django 2.1.5 on 2020-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200214_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowStudentUploadWithPartners',
            field=models.BooleanField(default=False, help_text='A boolean field. If true, students will be allowed to invite partners to their submission.'),
        ),
    ]
