# Generated by Django 6.0.2 on 2026-03-26 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_increase_testcase_description_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title for this conversation (auto-generated or user-set)",
                        max_length=200,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Rolling summary of older messages for context window management",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The assignment this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="core.assignment",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The submission this conversation is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="core.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The grader who owns this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-modified",),
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool_call", "Tool Call"),
                            ("tool_result", "Tool Result"),
                            ("summary", "Summary"),
                        ],
                        help_text="Who sent this message",
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="The message text content"
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the tool (for tool_call/tool_result roles)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "tool_args",
                    models.JSONField(
                        blank=True,
                        help_text="JSON arguments for the tool call",
                        null=True,
                    ),
                ),
                (
                    "tool_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Whether the tool call was approved or rejected by the user",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tokens in this message"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatconversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["submission", "user"], name="core_chatco_submiss_24b1e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["assignment", "user"], name="core_chatco_assignm_9bce96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created"],
                name="core_chatme_convers_b21702_idx",
            ),
        ),
    ]
