# Generated by Django 2.1.2 on 2020-03-03 21:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200221_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rosterMap',
            field=jsonfield.fields.JSONField(default={}, help_text='An map of LMS id to codePost student emails for this course.'),
        ),
    ]
