# Generated by Django 6.0.2 on 2026-03-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_chat_conversations"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_chat_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI chat assistant is disabled even if AI is globally enabled",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_chat_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI chat assistant is disabled at the organization level",
            ),
        ),
    ]
