# Generated by Django 2.1.2 on 2020-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200303_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='dependencies',
        ),
        migrations.AlterField(
            model_name='environment',
            name='dockerfile',
            field=models.TextField(blank=True, default='', help_text='A custom set of docker commands to append to the base image docker file'),
        ),
    ]
