# Generated by Django 6.0.2 on 2026-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_ai_chat_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagerecord",
            name="cached_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of input tokens served from provider cache (reduced cost)",
            ),
        ),
    ]
