# Generated by Django 6.0.2 on 2026-03-28 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_ai_usage_cached_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="endChar",
            field=models.IntegerField(
                help_text="The ending character offset of the comment. For code/markdown files: 0-indexed character position within the end line. For PDF text-selection comments: character offset in the page's text layer. For PDF region comments: values >= 1,000,000 encode a bounding box as MARKER + rightPct*101 + bottomPct (percentages 0-100 of page dimensions). For Jupyter notebooks (.ipynb): always 0 (comments target entire cells)."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="endLine",
            field=models.IntegerField(
                help_text="The line or position where the comment ends. For code/markdown files: 0-indexed line number. For PDF files: 1-based page number (usually same as startLine). For Jupyter notebooks (.ipynb): 0-based cell index (usually same as startLine)."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="feedback",
            field=models.IntegerField(
                default=0,
                help_text="Student feedback on this comment. Valid values: -1 (negative), 0 (none), 1 (positive). Only applicable when rubricComment is set.",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="startChar",
            field=models.IntegerField(
                help_text="The starting character offset of the comment. For code/markdown files: 0-indexed character position within the start line. For PDF text-selection comments: character offset in the page's text layer. For PDF region comments: values >= 1,000,000 encode a bounding box as MARKER + leftPct*101 + topPct (percentages 0-100 of page dimensions). For Jupyter notebooks (.ipynb): always 0 (comments target entire cells)."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="startLine",
            field=models.IntegerField(
                help_text="The line or position where the comment begins. For code/markdown files: 0-indexed line number. For PDF files: 1-based page number. For Jupyter notebooks (.ipynb): 0-based cell index."
            ),
        ),
        migrations.CreateModel(
            name="CourseAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submission_attempt", "Submission Attempt"),
                            ("submission_failed", "Submission Failed"),
                            ("file_view", "File View"),
                            ("feedback_view", "Feedback View"),
                            ("regrade_request", "Regrade Request"),
                            ("regrade_deleted", "Regrade Deleted"),
                            ("autograder_triggered", "Autograder Triggered"),
                            ("autograder_completed", "Autograder Completed"),
                            ("autograder_failed", "Autograder Failed"),
                            ("late_day_used", "Late Day Used"),
                        ],
                        help_text="The type of event",
                        max_length=32,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="Extra context for the event (error messages, counts, etc.)",
                        null=True,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.course",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The submission associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["course", "-created"],
                        name="core_course_course__e36275_idx",
                    ),
                    models.Index(
                        fields=["course", "event_type"],
                        name="core_course_course__c509b6_idx",
                    ),
                    models.Index(
                        fields=["course", "user"], name="core_course_course__0b0719_idx"
                    ),
                ],
            },
        ),
    ]
