# Generated by Django 2.1.2 on 2020-04-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200331_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='language',
            field=models.CharField(choices=[('python-3.7', 'python-3.7'), ('python-2.7', 'python-2.7'), ('java', 'java'), ('c/c++', 'c/c++'), ('javascript', 'javascript'), ('haskell', 'haskell'), ('ocaml', 'ocaml'), ('ruby', 'ruby'), ('php', 'php'), ('other', 'other')], default='python-3.7', max_length=25),
        ),
    ]
