# Generated by Django 6.0.2 on 2026-03-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_add_course_audit_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
    ]
