# Generated by Django 2.1.2 on 2020-04-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200403_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='emailWhitelist',
            field=models.TextField(blank=True, help_text='Permissible student email domains.'),
        ),
    ]
