# Generated by Django 2.1.2 on 2020-04-09 18:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200408_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='dockerRunInstructions',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text='Instructions to be added to the docker file with a RUN command.'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='maxExposedFailedTests',
            field=models.PositiveIntegerField(blank=True, help_text='An integer field indicating the limit of the number of failed tests that will be exposed to a student (nudge mode).', null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='maxStudentTestRuns',
            field=models.PositiveIntegerField(blank=True, help_text='An integer field indicating the max times that tests will be run if tests are exposed.', null=True),
        ),
    ]
