# Generated by Django 6.0.2 on 2026-03-31 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_remove_agentic_chat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="ai_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated description of the assignment used as context for AI grading features. Editable by course admins, visible to graders. Not shown to students.",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="ai_description_locked",
            field=models.BooleanField(
                default=False,
                help_text="When True, prevents automatic regeneration of ai_description from new submissions.",
            ),
        ),
        migrations.AlterField(
            model_name="aiusagerecord",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("comment_generation", "Comment Generation"),
                    ("suggested_comments", "Suggested Comments"),
                    ("submission_summary", "Submission Summary"),
                    ("assignment_description", "Assignment Description"),
                    ("code_review", "Code Review"),
                    ("feedback", "Feedback"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of AI request",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "text",
                    models.TextField(
                        help_text="Markdown-formatted summary of the submission."
                    ),
                ),
                (
                    "generationMetadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata about the generation (model used, tokens, etc.).",
                        null=True,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="The submission this summary describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "submission summaries",
            },
        ),
        migrations.CreateModel(
            name="SuggestedComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="The AI-generated comment text."
                    ),
                ),
                (
                    "startLine",
                    models.IntegerField(
                        help_text="The line or position where the suggestion begins (same semantics as Comment.startLine)."
                    ),
                ),
                (
                    "endLine",
                    models.IntegerField(
                        help_text="The line or position where the suggestion ends (same semantics as Comment.endLine)."
                    ),
                ),
                (
                    "startChar",
                    models.IntegerField(
                        default=0,
                        help_text="The starting character offset (same semantics as Comment.startChar).",
                    ),
                ),
                (
                    "endChar",
                    models.IntegerField(
                        default=0,
                        help_text="The ending character offset (same semantics as Comment.endChar).",
                    ),
                ),
                (
                    "pointDelta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI-suggested point delta. Null if linked to a rubricComment.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of this suggestion.",
                        max_length=10,
                    ),
                ),
                (
                    "generationMetadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata about the generation (model used, tokens, confidence, etc.).",
                        null=True,
                    ),
                ),
                (
                    "acceptedBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The grader who accepted this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "acceptedComment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The real Comment created when this suggestion was accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_suggestion",
                        to="core.comment",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="The file this suggestion targets.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_comments",
                        to="core.submissionfile",
                    ),
                ),
                (
                    "rubricComment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional rubric comment the AI mapped this suggestion to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_comments",
                        to="core.rubriccomment",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The submission this suggestion belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_comments",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("file", "startLine", "startChar"),
                "indexes": [
                    models.Index(
                        fields=["submission", "status"],
                        name="core_sugges_submiss_5cd656_idx",
                    )
                ],
            },
        ),
    ]
