# Generated by Django 2.1.2 on 2020-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20200409_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='inviteCode',
            field=models.CharField(help_text='A token which allows students to join course.', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inviteCodeEnabled',
            field=models.BooleanField(default=False, help_text="If True, the course's invite code can be used."),
        ),
    ]
