# Generated by Django 2.1.2 on 2020-04-13 18:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200412_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activateQueue',
            field=models.BooleanField(default=True, help_text='If True, will be able to claim submissions from the ungraded queue.'),
        ),
        migrations.AddField(
            model_name='course',
            name='studentCaptions',
            field=jsonfield.fields.JSONField(default={}, help_text='Map student emails to captions.'),
        ),
        migrations.AddField(
            model_name='course',
            name='useStudentCaptions',
            field=models.BooleanField(default=False, help_text='If True, graders will see student captions (where defined) instead of emails.'),
        ),
    ]
