# Generated by Django 6.0.2 on 2026-03-31 23:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_ai_grading_assistance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable experiment name.", max_length=128
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("comment_generation", "Comment Generation"),
                            ("test_generation", "Test Generation"),
                            ("chat", "Chat"),
                            ("suggested_comments", "Suggested Comments"),
                            ("submission_summary", "Submission Summary"),
                            ("assignment_description", "Assignment Description"),
                        ],
                        help_text="Which AI feature is being tested.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="paused",
                        help_text="Current experiment lifecycle state.",
                        max_length=16,
                    ),
                ),
                (
                    "sample_rate",
                    models.FloatField(
                        default=0.1,
                        help_text="Fraction of requests that trigger dual generation (0.0–1.0).",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the experiment was completed.",
                        null=True,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who started this experiment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_experiments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                help_text="The A/B experiment this request was part of, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_records",
                to="core.promptexperiment",
            ),
        ),
        migrations.CreateModel(
            name="SystemPromptVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("comment_generation", "Comment Generation"),
                            ("test_generation", "Test Generation"),
                            ("chat", "Chat"),
                            ("suggested_comments", "Suggested Comments"),
                            ("submission_summary", "Submission Summary"),
                            ("assignment_description", "Assignment Description"),
                        ],
                        help_text="Which AI feature this prompt is used for.",
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label (e.g. 'Concise Feedback v2').",
                        max_length=128,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The prompt template. May contain {placeholder} variables."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("candidate", "Candidate"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        help_text="Lifecycle status. Only one variant per prompt_type may be 'active'.",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number within this prompt's lineage.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata (auto-generation context, improvement notes, etc.).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who created this variant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompt_variants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The variant this was derived from (for lineage tracking).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.systempromptvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="PromptFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "rating",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Standalone rating: 1 = thumbs up, -1 = thumbs down.",
                        null=True,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional free-text explanation.",
                    ),
                ),
                (
                    "ai_output_a",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Generated text from variant A (or the only variant for non-A/B).",
                    ),
                ),
                (
                    "ai_output_b",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Generated text from variant B (A/B test only).",
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("comment_generation", "Comment Generation"),
                            ("test_generation", "Test Generation"),
                            ("chat", "Chat"),
                            ("suggested_comments", "Suggested Comments"),
                            ("submission_summary", "Submission Summary"),
                            ("assignment_description", "Assignment Description"),
                        ],
                        help_text="Denormalized for efficient querying.",
                        max_length=32,
                    ),
                ),
                (
                    "is_custom_context",
                    models.BooleanField(
                        default=False,
                        help_text="True when the assignment had a custom ai_system_prompt override.",
                    ),
                ),
                (
                    "context_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of the input context to detect equivalent re-tests.",
                        max_length=64,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The experiment this feedback is part of (null for standalone rating).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="core.promptexperiment",
                    ),
                ),
                (
                    "usage_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the AIUsageRecord for cost/token tracking.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_feedback",
                        to="core.aiusagerecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The grader who provided this feedback.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chosen_variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="For A/B: the variant the user preferred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_chosen",
                        to="core.systempromptvariant",
                    ),
                ),
                (
                    "variant_used",
                    models.ForeignKey(
                        help_text="The variant that produced the rated output.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_received",
                        to="core.systempromptvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="promptexperiment",
            name="variant_a",
            field=models.ForeignKey(
                help_text="The control variant (usually the current active prompt).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments_as_a",
                to="core.systempromptvariant",
            ),
        ),
        migrations.AddField(
            model_name="promptexperiment",
            name="variant_b",
            field=models.ForeignKey(
                help_text="The challenger variant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments_as_b",
                to="core.systempromptvariant",
            ),
        ),
        migrations.AddField(
            model_name="aiusagerecord",
            name="prompt_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="The prompt variant used for this request (for A/B tracking).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_records",
                to="core.systempromptvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="systempromptvariant",
            index=models.Index(
                fields=["prompt_type", "status"], name="core_system_prompt__2fae09_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="systempromptvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("prompt_type",),
                name="unique_active_prompt_per_type",
            ),
        ),
        migrations.AddIndex(
            model_name="promptfeedback",
            index=models.Index(
                fields=["prompt_type", "is_custom_context"],
                name="core_prompt_prompt__67a9e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptfeedback",
            index=models.Index(
                fields=["experiment", "-created"], name="core_prompt_experim_505540_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptexperiment",
            index=models.Index(
                fields=["prompt_type", "status"], name="core_prompt_prompt__510b24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptexperiment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("prompt_type",),
                name="unique_running_experiment_per_type",
            ),
        ),
    ]
