# Generated by Django 2.1.2 on 2020-04-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200413_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccomment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
