# Generated by Django 2.1.2 on 2020-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20200414_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text='The name of the file.', max_length=150),
        ),
        migrations.AlterField(
            model_name='filetemplate',
            name='name',
            field=models.CharField(help_text='The name of the template file.', max_length=150),
        ),
    ]
