# Generated by Django 6.0.2 on 2026-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_seed_default_prompts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptLabSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_improve_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch for all automatic prompt improvement.",
                    ),
                ),
                (
                    "schedule_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable periodic (Celery beat) auto-improvement runs.",
                    ),
                ),
                (
                    "schedule_interval_hours",
                    models.PositiveIntegerField(
                        default=168,
                        help_text="How often (in hours) the scheduled task checks for improvements.",
                    ),
                ),
                (
                    "threshold_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable auto-improvement when new feedback count crosses the threshold.",
                    ),
                ),
                (
                    "feedback_threshold",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Number of new default-pool feedback entries (since last auto-improve) to trigger generation.",
                    ),
                ),
                (
                    "min_feedback",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum total feedback required before any auto-improvement can run.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Lab Settings",
                "verbose_name_plural": "Prompt Lab Settings",
            },
        ),
    ]
