# Generated by Django 2.1.2 on 2020-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200420_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enableStudentFeedbackNotifications',
            field=models.BooleanField(default=False, help_text='If True, the graders may send students feedback notifications.'),
        ),
    ]
