# Generated by Django 6.0.2 on 2026-04-01 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_prompt_lab_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionsummary",
            name="regenerationCount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this summary has been regenerated.",
            ),
        ),
        migrations.AddField(
            model_name="suggestedcomment",
            name="firstViewedAt",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when a grader first saw this suggestion (set on list fetch).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="suggestedcomment",
            name="generationBatch",
            field=models.UUIDField(
                blank=True,
                help_text="UUID grouping all suggestions from a single generation call.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="suggestedcomment",
            name="promptVariant",
            field=models.ForeignKey(
                blank=True,
                help_text="The prompt variant used to generate this suggestion.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_comments",
                to="core.systempromptvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcomment",
            index=models.Index(
                fields=["promptVariant", "status"],
                name="core_sugges_promptV_37965c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcomment",
            index=models.Index(
                fields=["generationBatch"], name="core_sugges_generat_e65587_idx"
            ),
        ),
    ]
