# Generated by Django 6.0.2 on 2026-04-01 19:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_remove_chat_prompt_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptlabsettings",
            name="ai_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="API key for the auto-improvement AI provider (stored encrypted).",
            ),
        ),
        migrations.AddField(
            model_name="promptlabsettings",
            name="ai_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model to use for auto-improvement (e.g. gemini-2.5-pro, gpt-4o).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="promptlabsettings",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[("gemini", "Google Gemini"), ("openai", "OpenAI")],
                default="",
                help_text="AI provider used for auto-improvement and prompt generation.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="promptexperiment",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature is being tested.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="promptfeedback",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Denormalized for efficient querying.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="systempromptvariant",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature this prompt is used for.",
                max_length=32,
            ),
        ),
    ]
