# Generated by Django 3.2.18 on 2023-12-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20200503_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='solutionStatus',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='statusOnSolution',
        ),
    ]
