# Generated by Django 3.2.18 on 2024-04-13 16:26

import core.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_manual_faked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='manual_payments',
            field=jsonfield.fields.JSONField(blank=True, default=list, help_text='An array of manual payments', validators=[core.models.Course.validate_manual_payments]),
        ),
        migrations.AddField(
            model_name='course',
            name='waiver_requested',
            field=models.BooleanField(default=False, help_text='If True, the course has requested a waiver.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='inviteCode',
            field=models.CharField(blank=True, help_text='A token which allows students to join course.', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rosterMap',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='An map of LMS id to codePost student emails for this course.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='studentCaptions',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='Map student emails to captions.'),
        ),
    ]
