# Generated by Django 6.0.2 on 2026-04-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_promptlab_ai_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptfeedback",
            name="variant_used",
            field=models.ForeignKey(
                blank=True,
                help_text="The variant that produced the rated output (null when variant is unknown, e.g. pre-existing summaries).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_received",
                to="core.systempromptvariant",
            ),
        ),
    ]
