# Generated by Django 6.0.2 on 2026-04-02 18:03

import jsonfield.fields
from django.db import migrations


def migrate_comments_disabled(apps, schema_editor):
    """Copy ai_comments_disabled=True into ai_feature_config for both Org and Course."""
    Organization = apps.get_model('core', 'Organization')
    Course = apps.get_model('core', 'Course')

    for org in Organization.objects.filter(ai_comments_disabled=True):
        config = org.ai_feature_config or {}
        config['comment_generation'] = False
        org.ai_feature_config = config
        org.save(update_fields=['ai_feature_config'])

    for course in Course.objects.filter(ai_comments_disabled=True):
        config = course.ai_feature_config or {}
        config['comment_generation'] = False
        course.ai_feature_config = config
        course.save(update_fields=['ai_feature_config'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_feedback_variant_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_feature_config",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Per-feature AI toggles. JSON: {"comment_generation": true, "suggested_comments": false, ...}. Missing keys use defaults (enabled).',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_feature_config",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Per-feature AI toggles. JSON: {"comment_generation": true, "suggested_comments": false, ...}. Missing keys use defaults (enabled).',
            ),
        ),
        migrations.RunPython(migrate_comments_disabled, migrations.RunPython.noop),
    ]
