# Generated by Django 6.0.2 on 2026-04-10 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_ai_feature_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimetoken",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the JWT issued from this OTT is scoped to this course.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="one_time_tokens",
                to="core.course",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="isServiceAccount",
            field=models.BooleanField(
                default=False,
                help_text="If True, this user is an auto-created service account for a course API key.",
            ),
        ),
        migrations.CreateModel(
            name="CourseAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        help_text="A human-readable label for this key.", max_length=128
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First characters of the raw key, used for fast lookup.",
                        max_length=32,
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(
                        help_text="SHA-256 hash of the full raw key.", max_length=128
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="If False, the key is revoked."
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this key was used to authenticate.",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this key is scoped to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="core.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The admin who created this key.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_course_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course API Key",
                "verbose_name_plural": "Course API Keys",
                "unique_together": {("course", "name")},
            },
        ),
    ]
