# Generated by Django 6.0.2 on 2026-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_course_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_main_org",
            field=models.BooleanField(
                default=False,
                help_text="If True, this organization is the main/default organization. Only one organization can be the main org at a time. The main org's SSO is used as the default login method.",
            ),
        ),
    ]
