# Generated by Django 6.0.2 on 2026-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_add_is_main_org_to_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allowed_email_domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Additional email domains that should map to this organization for SSO lookup (e.g. subdomains like scarletmail.rutgers.edu).",
            ),
        ),
    ]
