# Generated by Django 6.0.2 on 2026-05-14 00:00

from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE, SET_NULL
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0083_organization_allowed_email_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFileInstructorEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=now, editable=False)),
                ('modified', models.DateTimeField(default=now)),
                (
                    'data',
                    models.TextField(
                        default='',
                        help_text='The persisted instructor-edited contents for this submission file.',
                    ),
                ),
                (
                    'file',
                    models.OneToOneField(
                        help_text='The submission file this persisted instructor edit belongs to.',
                        on_delete=CASCADE,
                        related_name='instructorEdit',
                        to='core.submissionfile',
                    ),
                ),
                (
                    'lastEditedBy',
                    models.ForeignKey(
                        blank=True,
                        help_text='The most recent user to save this persisted instructor edit.',
                        null=True,
                        on_delete=SET_NULL,
                        related_name='submission_file_edits',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={},
        ),
    ]
