# Generated by Django 6.0.4 on 2026-05-15 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_submissionfileinstructoredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="If True, students see only pass/fail status and point impact — not the test name, logs, or explanation.",
            ),
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shortId",
                    models.CharField(
                        help_text="Short identifier used in test decorators, e.g. 'recursion'.",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the learning objective.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional longer description of the objective.",
                    ),
                ),
                (
                    "visibilityMode",
                    models.CharField(
                        choices=[
                            ("always", "Always show"),
                            ("on_pass", "Show when tests pass"),
                            ("on_fail", "Show when tests fail"),
                            ("never", "Admin only"),
                        ],
                        default="always",
                        help_text="Controls when students can see this objective in test results.",
                        max_length=16,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="The related assignment__id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learningObjectives",
                        to="core.assignment",
                    ),
                ),
            ],
            options={
                "unique_together": {("shortId", "assignment")},
            },
        ),
        migrations.AddField(
            model_name="testcase",
            name="learningObjectives",
            field=models.ManyToManyField(
                blank=True,
                help_text="Learning objectives this test is associated with.",
                related_name="testCases",
                to="core.learningobjective",
            ),
        ),
    ]
