# Generated by Django 6.0.4 on 2026-06-25 20:47

import core.models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_learningobjective_aggregation_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the question bank.", max_length=128
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the bank."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually authored"),
                            ("canvas", "Imported from Canvas"),
                            ("ai", "Accepted from an AI suggestion"),
                        ],
                        default="manual",
                        help_text="Where this bank originated (staff-internal provenance).",
                        max_length=16,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionBanks",
                        to="core.course",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who created this bank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("course", "name")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "questionType",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice (one correct)"),
                            ("multiple_answers", "Multiple Answers (several correct)"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("numerical", "Numerical"),
                            ("code", "Code"),
                        ],
                        default="multiple_choice",
                        help_text="The type of question.",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The question stem/prompt (may contain HTML from Canvas)."
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Point value of the question.",
                        max_digits=6,
                    ),
                ),
                (
                    "generalFeedback",
                    models.TextField(
                        blank=True, help_text="Feedback shown regardless of answer."
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="For code questions: the language (matches Environment.language values). When null, resolve from the attached assignment's environment.",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "starterCode",
                    models.TextField(
                        blank=True,
                        help_text="For code questions: optional starter code shown to students.",
                        null=True,
                    ),
                ),
                (
                    "referenceSolution",
                    models.TextField(
                        blank=True,
                        help_text="For code questions: optional reference solution (authoring-only, not auto-graded).",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually authored"),
                            ("canvas", "Imported from Canvas"),
                            ("ai", "Accepted from an AI suggestion"),
                        ],
                        default="manual",
                        help_text="Where this question originated (staff-internal provenance).",
                        max_length=16,
                    ),
                ),
                (
                    "metadata",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Staff-internal metadata (Canvas IDs, AI provenance). Never shown to students.",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.course",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who authored/accepted this question.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "banks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The question banks this question belongs to (a question may be in several).",
                        related_name="questions",
                        to="core.questionbank",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "text",
                    models.TextField(
                        help_text="The choice text (or accepted answer value)."
                    ),
                ),
                (
                    "isCorrect",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this choice is a correct answer.",
                    ),
                ),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0, help_text="Order of this choice within the question."
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Optional per-choice feedback."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The related question_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "title",
                    models.CharField(help_text="The quiz title.", max_length=128),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional quiz description."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually authored"),
                            ("canvas", "Imported from Canvas"),
                            ("ai", "Accepted from an AI suggestion"),
                        ],
                        default="manual",
                        help_text="Where this quiz originated (staff-internal provenance).",
                        max_length=16,
                    ),
                ),
                (
                    "metadata",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Staff-internal metadata (Canvas IDs, etc.).",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment this quiz is attached to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="core.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="core.course",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who created this quiz.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="QuizImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded Canvas QTI/Common Cartridge export.",
                        upload_to=core.models.quiz_import_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the import job.",
                        max_length=16,
                    ),
                ),
                (
                    "taskId",
                    models.CharField(
                        blank=True,
                        help_text="Celery task id for polling.",
                        max_length=191,
                    ),
                ),
                (
                    "createdQuizCount",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of quizzes created."
                    ),
                ),
                (
                    "createdQuestionCount",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of questions created."
                    ),
                ),
                (
                    "errorMessage",
                    models.TextField(
                        blank=True, help_text="Error detail if the job failed."
                    ),
                ),
                (
                    "summary",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-item parse report, including skipped/unsupported types.",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_import_jobs",
                        to="core.course",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who started the import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quiz_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "targetBank",
                    models.ForeignKey(
                        blank=True,
                        help_text="The bank imported questions land in. Created if absent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to="core.questionbank",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0, help_text="Order of this question within the quiz."
                    ),
                ),
                (
                    "pointsOverride",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional per-quiz point override. Null uses Question.points.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The related question_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizMemberships",
                        to="core.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The related quiz_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizQuestions",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                help_text="The questions in this quiz (ordered via QuizQuestion).",
                related_name="quizzes",
                through="core.QuizQuestion",
                to="core.question",
            ),
        ),
        migrations.CreateModel(
            name="SuggestedQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "questionType",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice (one correct)"),
                            ("multiple_answers", "Multiple Answers (several correct)"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("numerical", "Numerical"),
                            ("code", "Code"),
                        ],
                        default="multiple_choice",
                        help_text="The suggested question type.",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The suggested question stem/prompt."),
                ),
                (
                    "choicesData",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="Proposed choices: list of {text, isCorrect, feedback}.",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Suggested point value.",
                        max_digits=6,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="For code suggestions: the language.",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "starterCode",
                    models.TextField(
                        blank=True, help_text="Suggested starter code.", null=True
                    ),
                ),
                (
                    "referenceSolution",
                    models.TextField(
                        blank=True, help_text="Suggested reference solution.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of this suggestion.",
                        max_length=10,
                    ),
                ),
                (
                    "generationMetadata",
                    jsonfield.fields.JSONField(
                        blank=True,
                        help_text="Metadata about the generation (model, tokens, etc.). Staff-internal.",
                        null=True,
                    ),
                ),
                (
                    "generationBatch",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID grouping all suggestions from a single generation call.",
                        null=True,
                    ),
                ),
                (
                    "acceptedBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The instructor who accepted this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_quiz_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "acceptedQuestion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The real Question created or updated when this suggestion was accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_suggestion",
                        to="core.question",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment this suggestion was generated for (fresh generation).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_quiz_questions",
                        to="core.assignment",
                    ),
                ),
                (
                    "promptVariant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prompt variant used to generate this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_quiz_questions",
                        to="core.systempromptvariant",
                    ),
                ),
                (
                    "sourceQuestion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The existing question this suggestion was generated from (cross-semester refresh).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regeneration_suggestions",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["assignment", "status"],
                        name="core_sugges_assignm_0c1c61_idx",
                    ),
                    models.Index(
                        fields=["sourceQuestion", "status"],
                        name="core_sugges_sourceQ_ecffdf_idx",
                    ),
                    models.Index(
                        fields=["generationBatch"],
                        name="core_sugges_generat_6a1112_idx",
                    ),
                ],
            },
        ),
    ]
