# Generated by Django 6.0.4 on 2026-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_quizzes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagerecord",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("comment_generation", "Comment Generation"),
                    ("suggested_comments", "Suggested Comments"),
                    ("submission_summary", "Submission Summary"),
                    ("assignment_description", "Assignment Description"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("code_review", "Code Review"),
                    ("feedback", "Feedback"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of AI request",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="promptexperiment",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature is being tested.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="promptfeedback",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Denormalized for efficient querying.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="systempromptvariant",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature this prompt is used for.",
                max_length=32,
            ),
        ),
    ]
