# Generated by Django 6.0.4 on 2026-06-25 21:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_quiz_usage_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this group (e.g. 'Chapter 3 — pick 3').",
                        max_length=128,
                    ),
                ),
                (
                    "pickCount",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many questions to randomly draw from the bank.",
                    ),
                ),
                (
                    "pointsPerQuestion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Points each drawn question is worth.",
                        max_digits=6,
                    ),
                ),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0, help_text="Order of this group within the quiz."
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        help_text="The bank questions are drawn from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_groups",
                        to="core.questionbank",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The related quiz_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionGroups",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
            },
        ),
    ]
