# Generated by Django 6.0.4 on 2026-06-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_quiz_question_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional Markdown description shown beneath the stem (rich content: code blocks, lists, formatting).",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(
                help_text="The question stem/prompt — single font (may contain HTML from Canvas)."
            ),
        ),
    ]
