# Generated by Django 6.0.4 on 2026-06-25 22:28

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_question_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unguessable public token used in the image URL.",
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="The uploaded image file.",
                        upload_to=core.models.quiz_image_upload_path,
                    ),
                ),
                (
                    "originalName",
                    models.CharField(
                        blank=True, help_text="Original filename.", max_length=255
                    ),
                ),
                (
                    "contentType",
                    models.CharField(
                        blank=True, help_text="Image MIME type.", max_length=100
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_images",
                        to="core.course",
                    ),
                ),
                (
                    "uploadedBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who uploaded it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_quiz_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
