# Generated by Django 6.0.4 on 2026-06-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_quiz_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="assignments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assignments this bank serves. Auto-added when the bank is used in a quiz attached to an assignment; editable by instructors. Used as AI-generation context.",
                related_name="questionBanks",
                to="core.assignment",
            ),
        ),
    ]
