# Generated by Django 6.0.4 on 2026-06-26 15:26

import core.models
from django.db import migrations, models


def _rename_source(apps, schema_editor, old, new):
    for model_name in ("QuestionBank", "Question", "Quiz"):
        model = apps.get_model("core", model_name)
        model.objects.filter(source=old).update(source=new)


def forwards(apps, schema_editor):
    _rename_source(apps, schema_editor, "canvas", "imported")


def backwards(apps, schema_editor):
    _rename_source(apps, schema_editor, "imported", "canvas")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_bank_assignments"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manually authored"),
                    ("imported", "Imported"),
                    ("ai", "Accepted from an AI suggestion"),
                ],
                default="manual",
                help_text="Where this question originated (staff-internal provenance).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manually authored"),
                    ("imported", "Imported"),
                    ("ai", "Accepted from an AI suggestion"),
                ],
                default="manual",
                help_text="Where this bank originated (staff-internal provenance).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manually authored"),
                    ("imported", "Imported"),
                    ("ai", "Accepted from an AI suggestion"),
                ],
                default="manual",
                help_text="Where this quiz originated (staff-internal provenance).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="quizimportjob",
            name="file",
            field=models.FileField(
                help_text="The uploaded QTI / Common Cartridge export.",
                upload_to=core.models.quiz_import_upload_path,
            ),
        ),
    ]
