# Generated by Django 6.0.4 on 2026-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_question_bank_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="assignmentTrigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("during", "During the assignment"),
                    ("after_assignment", "After the assignment closes"),
                    ("after_submission", "After the student submits"),
                    ("after_feedback", "After feedback is released"),
                ],
                default="during",
                help_text="When an attached quiz becomes available, relative to the assignment lifecycle. Ignored for standalone quizzes.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="attemptsAllowed",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of attempts allowed. 0 = unlimited."
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="availableFrom",
            field=models.DateTimeField(
                blank=True,
                help_text="Standalone quizzes: when the quiz opens.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="availableUntil",
            field=models.DateTimeField(
                blank=True,
                help_text="Standalone quizzes: when the quiz closes / is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="isPublished",
            field=models.BooleanField(
                default=False,
                help_text="If false the quiz is a draft (author-only); students only see published quizzes.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="passingScore",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional pass threshold, as a percentage (0–100).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="showCorrectAnswers",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("after_submit", "After submitting"),
                    ("after_close", "After the quiz closes"),
                ],
                default="after_submit",
                help_text="When students may see the correct answers.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="shuffleQuestions",
            field=models.BooleanField(
                default=False, help_text="Randomize question order per attempt."
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="timeLimitMinutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time limit in minutes. Null = untimed.",
                null=True,
            ),
        ),
    ]
