# Generated by Django 6.0.4 on 2026-06-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_quiz_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="assignmentTrigger",
            field=models.CharField(
                choices=[
                    ("during", "During the assignment"),
                    ("after_assignment", "After the assignment closes"),
                    ("after_submission", "After the student submits"),
                    ("after_feedback", "After feedback is released"),
                ],
                default="during",
                help_text="When an attached quiz becomes available, relative to the assignment lifecycle. Ignored for standalone quizzes.",
                max_length=20,
            ),
        ),
    ]
