# Generated by Django 6.0.4 on 2026-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_alter_quiz_assignmenttrigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="passingScoreUnit",
            field=models.CharField(
                choices=[("percent", "Percent"), ("points", "Points")],
                default="percent",
                help_text="Whether passingScore is a percentage or an absolute point value.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="passingScore",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional pass threshold. Interpreted per passingScoreUnit (a percentage 0–100, or an absolute point value).",
                max_digits=7,
                null=True,
            ),
        ),
    ]
