# Generated by Django 6.0.4 on 2026-06-29 19:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_quiz_passingscoreunit_alter_quiz_passingscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="scoringPolicy",
            field=models.CharField(
                choices=[
                    ("highest", "Highest attempt counts"),
                    ("latest", "Latest attempt counts"),
                    ("average", "Average of attempts"),
                ],
                default="highest",
                help_text="Which attempt counts as the official score when multiple attempts are allowed.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attemptNumber",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1-based attempt index for this (quiz, student).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                        ],
                        default="in_progress",
                        help_text="Attempt lifecycle state.",
                        max_length=16,
                    ),
                ),
                (
                    "startedAt",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the student started this attempt.",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hard stop = startedAt + quiz.timeLimitMinutes. Null when untimed.",
                        null=True,
                    ),
                ),
                (
                    "submittedAt",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the attempt was submitted.",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-graded points earned (set on submit).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "maxScore",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total points possible in this attempt (snapshot).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "needsManualGrading",
                    models.BooleanField(
                        default=False,
                        help_text="True if any response (essay/code) awaits manual grading.",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the attempt met quiz.passingScore. Null until fully graded or if no threshold.",
                        null=True,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The quiz being attempted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student taking the quiz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("attemptNumber",),
                "unique_together": {("quiz", "student", "attemptNumber")},
            },
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0,
                        help_text="Presentation order within the attempt (randomized when shuffleQuestions).",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Points this question is worth in this attempt (snapshot of override/base).",
                        max_digits=6,
                    ),
                ),
                (
                    "answerText",
                    models.TextField(
                        blank=True,
                        help_text="Typed answer for short-answer/numerical/essay/code questions.",
                    ),
                ),
                (
                    "pointsEarned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Points awarded after grading. Null until graded.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "isCorrect",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the auto-graded answer was correct. Null for manual/ungraded.",
                        null=True,
                    ),
                ),
                (
                    "needsManualGrading",
                    models.BooleanField(
                        default=False,
                        help_text="True for essay/code responses awaiting manual grading.",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        help_text="The attempt this response belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question presented (snapshot).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.question",
                    ),
                ),
                (
                    "selectedChoices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Selected option(s) for choice-based questions.",
                        related_name="+",
                        to="core.questionchoice",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
