# Generated by Django 6.0.4 on 2026-06-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_quiz_scoringpolicy_quizattempt_quizresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allowBacktracking",
            field=models.BooleanField(
                default=True,
                help_text="When sequential, whether students may return to previous questions.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="oneQuestionAtATime",
            field=models.BooleanField(
                default=False,
                help_text="Sequential mode: show one question at a time instead of all on one page.",
            ),
        ),
    ]
