# Generated by Django 6.0.4 on 2026-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_quiz_allowbacktracking_quiz_onequestionatatime"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="feedbackReleasedAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When feedbackReleased was last set true. Anchors quiz close times relative to feedback release.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="closeEvent",
            field=models.CharField(
                choices=[
                    ("none", "No automatic close"),
                    ("assignment_due", "At the assignment's deadline"),
                    ("submission", "After the student submits"),
                    ("feedback_released", "When feedback is released"),
                    ("fixed_date", "At a fixed date & time"),
                ],
                default="none",
                help_text="When an attached quiz closes. Ignored for standalone quizzes.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="closeOffsetMinutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minutes added to the close event (e.g. 10080 = one week after). Ignored for 'none' and 'fixed_date'.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="endAttemptsAtClose",
            field=models.BooleanField(
                default=False,
                help_text="If true, reaching the close time ends/auto-submits in-progress attempts (hard deadline); if false it only blocks new attempts.",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="availableUntil",
            field=models.DateTimeField(
                blank=True,
                help_text="Standalone quizzes: when the quiz closes / is due. Also the close time when an attached quiz's closeEvent is 'fixed_date'.",
                null=True,
            ),
        ),
    ]
