# Generated by Django 6.0.4 on 2026-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_assignment_feedbackreleasedat_quiz_closeevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="assignmentTrigger",
            field=models.CharField(
                choices=[
                    ("during", "During the assignment"),
                    ("after_assignment", "After the assignment closes"),
                    ("after_submission", "After the student submits"),
                    ("after_feedback", "After feedback is released (whole assignment)"),
                    (
                        "after_student_feedback",
                        "After each student's feedback is ready (self-paced)",
                    ),
                ],
                default="during",
                help_text="When an attached quiz becomes available, relative to the assignment lifecycle. Ignored for standalone quizzes.",
                max_length=32,
            ),
        ),
    ]
