# Generated by Django 6.0.4 on 2026-07-07 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_courseauditevent_quiz_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="quizGraders",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of usernames of graders for the course who are allowed to grade quizzes. Course admins can always grade quizzes.",
                related_name="quizGrader_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizresponse",
            name="gradedBy",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff user who manually graded this response.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizresponse",
            name="graderFeedback",
            field=models.TextField(
                blank=True,
                help_text="Optional feedback from the grader on a manually graded response.",
            ),
        ),
    ]
