# Generated by Django 6.0.4 on 2026-07-08 20:13

import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_backfill_feedback_released_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="autoPublishGenerated",
            field=models.BooleanField(
                default=False,
                help_text="If true, per-student generated question sets are approved automatically on generation (no staff review gate).",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="gradersCanReviewGenerated",
            field=models.BooleanField(
                default=False,
                help_text="If true, graders may review/edit/approve per-student generated question sets on this quiz; if false, only course admins may.",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready for review"),
                            ("approved", "Approved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Lifecycle: pending -> generating -> ready (awaiting review) -> approved; or failed.",
                        max_length=12,
                    ),
                ),
                (
                    "approvedAt",
                    models.DateTimeField(
                        blank=True, help_text="When this set was approved.", null=True
                    ),
                ),
                (
                    "generationBatch",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the generation run that produced/claimed this set. A stale task whose batch no longer matches must not write results.",
                        null=True,
                    ),
                ),
                (
                    "generationMetadata",
                    jsonfield.fields.JSONField(
                        blank=True,
                        help_text="Metadata about the generation (model, tokens, etc.). Staff-internal.",
                        null=True,
                    ),
                ),
                (
                    "errorMessage",
                    models.TextField(
                        blank=True, help_text="Error detail if generation failed."
                    ),
                ),
                (
                    "approvedBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who approved this set. Null when auto-published.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_generated_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promptVariant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The platform prompt variant used to generate this set.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_question_sets",
                        to="core.systempromptvariant",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The related quiz_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generatedSets",
                        to="core.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student this set was generated for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_question_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The submission this set was generated from (seed). Null if the submission was later deleted; regeneration then requires a new submission.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_question_sets",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="QuizGeneratedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this section (e.g. 'About your solution — 3 questions').",
                        max_length=128,
                    ),
                ),
                (
                    "systemPrompt",
                    models.TextField(
                        help_text="Instructor-authored prompt template. May contain {variables} such as {assignment_file:name} or {submission_files}, resolved per student at generation time."
                    ),
                ),
                (
                    "numQuestions",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How many questions to generate per student.",
                    ),
                ),
                (
                    "pointsPerQuestion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Points each generated question is worth.",
                        max_digits=6,
                    ),
                ),
                (
                    "questionTypes",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional subset of question types to generate (QUESTION_TYPE_CHOICES keys). Empty = let the model choose.",
                    ),
                ),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0, help_text="Order of this section within the quiz."
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The related quiz_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generatedSections",
                        to="core.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
            },
        ),
        migrations.CreateModel(
            name="GeneratedQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "questionType",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice (one correct)"),
                            ("multiple_answers", "Multiple Answers (several correct)"),
                            ("true_false", "True / False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("numerical", "Numerical"),
                            ("code", "Code"),
                        ],
                        default="multiple_choice",
                        help_text="The type of question.",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(help_text="The question stem/prompt.")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional Markdown description shown beneath the stem.",
                    ),
                ),
                (
                    "choicesData",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="Choices: list of {text, isCorrect, feedback}.",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Point value (seeded from the section's pointsPerQuestion, staff-editable).",
                        max_digits=6,
                    ),
                ),
                (
                    "sortKey",
                    models.IntegerField(
                        default=0, help_text="Order of this question within the set."
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="For code questions: the language.",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "starterCode",
                    models.TextField(
                        blank=True,
                        help_text="For code questions: optional starter code shown to students.",
                        null=True,
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        help_text="The related set_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.generatedquestionset",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The section this question was generated for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generatedQuestions",
                        to="core.quizgeneratedsection",
                    ),
                ),
            ],
            options={
                "ordering": ("sortKey", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="generatedquestionset",
            index=models.Index(
                fields=["quiz", "status"], name="core_genera_quiz_id_b22789_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="generatedquestionset",
            unique_together={("quiz", "student")},
        ),
    ]
