# Generated by Django 6.0.4 on 2026-07-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_quiz_autopublishgenerated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptexperiment",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("personalized_quiz_generation", "Personalized Quiz Questions"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature is being tested.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="promptfeedback",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("personalized_quiz_generation", "Personalized Quiz Questions"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Denormalized for efficient querying.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="systempromptvariant",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("assignment_description", "Assignment Description"),
                    ("comment_generation", "Comment Generation"),
                    ("personalized_quiz_generation", "Personalized Quiz Questions"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("submission_summary", "Submission Summary"),
                    ("suggested_comments", "Suggested Comments"),
                    ("test_generation", "Test Generation"),
                ],
                help_text="Which AI feature this prompt is used for.",
                max_length=32,
            ),
        ),
    ]
