# Generated by Django 6.0.4 on 2026-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_alter_promptexperiment_prompt_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
    ]
