# Generated by Django 6.0.4 on 2026-07-09 20:35

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_alter_promptexperiment_prompt_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_feature_models",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Per-feature AI model overrides. JSON: {"quiz_generation": "gemini-2.5-pro", ...}. Missing keys use the effective default model.',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_feature_models",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text='Per-feature AI model overrides. JSON: {"quiz_generation": "gemini-2.5-pro", ...}. Missing keys use ai_model.',
            ),
        ),
    ]
