# Generated by Django 6.0.4 on 2026-07-10 17:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_quiz_grading_audit_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="numericTolerance",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="For numerical questions: accept answers within ± this of an accepted value. Null/0 requires an exact match.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="partialCredit",
            field=models.BooleanField(
                default=False,
                help_text="For multiple_answers questions: score right-minus-wrong partial credit ((correct − incorrect selections) / total correct × points, floored at 0) instead of all-or-nothing.",
            ),
        ),
        migrations.CreateModel(
            name="QuizAccommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "timeMultiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Multiplier applied to every timed quiz's time limit for this student.",
                        max_digits=4,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this accommodation applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizAccommodations",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The accommodated student.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizAccommodations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "student")},
            },
        ),
    ]
