# Generated by Django 6.0.4 on 2026-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_quiz_grading_settings_and_accommodations"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="showResponses",
            field=models.BooleanField(
                default=True,
                help_text="Whether students may review their questions and answers after submitting. When false, students only see scores (per the reveal policy) — the question content is never shown again after submission.",
            ),
        ),
    ]
