# Generated by Django 6.0.4 on 2026-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_quiz_showresponses"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="isOfficialOverride",
            field=models.BooleanField(
                default=False,
                help_text="Staff-pinned: this attempt is the student's official score, overriding the quiz's scoringPolicy. At most one per (quiz, student).",
            ),
        ),
    ]
