# Generated by Django 6.0.4 on 2026-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_quizattempt_isofficialoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="ai_summary_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Per-assignment override of the submission-summary system prompt. Placeholders: {assignment_name}, {assignment_description}, {test_results}, {rubric}, {description_comparison}. Blank uses the global default.",
            ),
        ),
    ]
