# Generated by Django 6.0.4 on 2026-07-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_assignment_ai_summary_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedquizquestion",
            name="referenceSolution",
            field=models.TextField(
                blank=True,
                help_text="Grader-facing answer key generated alongside the question: the correct answer/code and, for hand-computation questions, the worked steps. NEVER shown to students and never snapshotted into questionSnapshot.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quizresponse",
            name="generatedQuestion",
            field=models.ForeignKey(
                blank=True,
                help_text="The per-student generated question this was drawn from (analytics/answer-key link only; may be deleted on regeneration). Grading/rendering use questionSnapshot, so this is nullable and SET_NULL.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.generatedquizquestion",
            ),
        ),
    ]
