# Generated by Django 6.0.4 on 2026-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_dataset_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="codeExecution",
            field=models.JSONField(
                blank=True,
                help_text="Staff-triggered sandbox run of a code answer: {status: running|success|error, stdout, stderr, images, error, executionTime, requestedBy, requestedAt, finishedAt}. Staff-internal — never shown to students.",
                null=True,
            ),
        ),
    ]
