# Generated by Django 6.0.4 on 2026-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_quiz_response_code_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allowSubmissionReview",
            field=models.BooleanField(
                default=True,
                help_text="Whether students may reopen and review a submitted attempt afterward. When false, submitting shows a confirmation only — the past attempt cannot be reopened (scores may still surface on the quiz card per the reveal policy).",
            ),
        ),
    ]
