# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 6.0.4 on 2026-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_split_show_correct_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="accessCode",
            field=models.CharField(
                blank=True,
                help_text="Optional code that lets a late student start this quiz after it has closed. Null/blank = no late access. Staff generate/rotate it via generateAccessCode; a correct code bypasses only the close, nothing else.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="closeBypassed",
            field=models.BooleanField(
                default=False,
                help_text="Started with the quiz access code after the close; its deadline is not capped at the close time.",
            ),
        ),
    ]
