# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 6.0.4 on 2026-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_quiz_accesscode_quizattempt_closebypassed"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="isPublic",
            field=models.BooleanField(
                default=False,
                help_text="If True, the file is downloadable without authentication via its public URL (courseFiles/raw/<id>/).",
            ),
        ),
    ]
