# Generated by Django 6.0.4 on 2026-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_coursefile_student_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagerecord",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("comment_generation", "Comment Generation"),
                    ("suggested_comments", "Suggested Comments"),
                    ("submission_summary", "Submission Summary"),
                    ("assignment_description", "Assignment Description"),
                    ("quiz_generation", "Quiz Question Suggestions"),
                    ("code_review", "Code Review"),
                    ("feedback", "Feedback"),
                    ("provider_test", "Provider Test"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of AI request",
                max_length=32,
            ),
        ),
    ]
