# Generated by Django 6.0.4 on 2026-08-05 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_alter_aiusagerecord_request_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSuggestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Queued"),
                            ("running", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the generation run.",
                        max_length=16,
                    ),
                ),
                (
                    "taskId",
                    models.CharField(
                        blank=True,
                        help_text="Celery task id, for debugging.",
                        max_length=191,
                    ),
                ),
                (
                    "createdCount",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of suggestions the run produced."
                    ),
                ),
                (
                    "errorMessage",
                    models.TextField(
                        blank=True, help_text="Friendly error detail if the run failed."
                    ),
                ),
                (
                    "generationBatch",
                    models.UUIDField(
                        blank=True,
                        help_text="Batch UUID of the suggestions this run created.",
                        null=True,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment suggestions were generated for (fresh generation).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_jobs",
                        to="core.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The related course_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_suggestion_jobs",
                        to="core.course",
                    ),
                ),
                (
                    "requestedBy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who requested the generation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_suggestion_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sourceQuestion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The existing question a refresh suggestion was generated from.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_jobs",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
