# Generated by Django 6.0.4 on 2026-08-05 21:53

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_quizsuggestionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsuggestionjob",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                help_text="The quiz a section-prompt test preview was run for (preview runs only).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_jobs",
                to="core.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quizsuggestionjob",
            name="resultData",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="Section-preview output: example questions, resolved prompt, seed info.",
            ),
        ),
    ]
