# Generated by Django 6.0.4 on 2026-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_quizsuggestionjob_quiz_quizsuggestionjob_resultdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="generationDate",
            field=models.DateTimeField(
                blank=True,
                help_text="Manual mode only: one-time scheduled run that generates question sets for students who have a submission but no set yet, at/after this time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="manualGeneration",
            field=models.BooleanField(
                default=False,
                help_text="If true, per-student question sets never generate automatically (no per-submission trigger, no backfill on publish or section creation) — staff generate via generateForStudent/generateMissing, or the one-time generationDate run.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="scheduledGenerationRanAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the scheduled generationDate run last fired (one-shot stamp). Moving generationDate past this re-arms the run.",
                null=True,
            ),
        ),
    ]
