# Generated by Django 6.0.4 on 2026-08-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_quiz_generationdate_quiz_manualgeneration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="manualGeneration",
            field=models.BooleanField(
                default=True,
                help_text="If true (the default), per-student question sets never generate automatically (no per-submission trigger, no backfill on publish or section creation) — staff generate via generateForStudent/generateMissing, or the one-time generationDate run.",
            ),
        ),
    ]
