# Generated by Django 6.0.4 on 2026-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0135_alter_quiz_manualgeneration"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedquizquestion",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional Markdown description shown beneath the stem (rich content: code blocks, lists, formatting).",
            ),
        ),
    ]
