# Generated by Django 6.0.4 on 2026-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0136_suggestedquizquestion_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="requireSebBrowser",
            field=models.BooleanField(
                default=False,
                help_text="If true, taking this quiz (starting, answering, submitting, and reading an in-progress attempt) requires Safe Exam Browser: requests must carry a valid X-SafeExamBrowser-ConfigKeyHash header matching sebConfigKey.",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="sebConfigKey",
            field=models.CharField(
                blank=True,
                help_text="SEB Config Key (64 hex chars) pasted by the instructor from the SEB Config Tool. Requests verify as SHA256(request URL + this key). Null/blank with requireSebBrowser on blocks students until a key is set.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="lockdownVerified",
            field=models.BooleanField(
                default=False,
                help_text="Started with a verified Safe Exam Browser signature. False on attempts started before requireSebBrowser was enabled (or by exempt students).",
            ),
        ),
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_access_code_changed", "Quiz Access Code Changed"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_started_late", "Quiz Attempt Started Late"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempt_seb_blocked", "Quiz Attempt SEB Blocked"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_response_graded", "Quiz Response Graded"),
                    ("quiz_response_grade_reopened", "Quiz Response Grade Reopened"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_unapproved",
                        "Generated Question Set Unapproved",
                    ),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
    ]
