# Generated by Django 6.0.4 on 2026-08-06 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_quiz_requiresebbrowser_quiz_sebconfigkey_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizaccommodation",
            name="sebExempt",
            field=models.BooleanField(
                default=False,
                help_text="Exempt this student from Safe Exam Browser requirements (e.g. they use a platform SEB doesn't run on, like Linux or ChromeOS). Their attempts show lockdownVerified=False to staff.",
            ),
        ),
        migrations.CreateModel(
            name="QuizSebLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "configKey",
                    models.CharField(
                        help_text="SEB Config Key computed from configPlist; request hashes verify against it.",
                        max_length=64,
                    ),
                ),
                (
                    "configPlist",
                    models.TextField(
                        help_text="The exact .seb plist served for this launch — stored verbatim so the served bytes always match the computed configKey."
                    ),
                ),
                (
                    "expiresAt",
                    models.DateTimeField(
                        help_text="When this launch's configKey stops verifying (generous — it must outlive the whole quiz session, unlike the embedded auth token)."
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="The quiz this launch opens.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sebLaunches",
                        to="core.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The launching student.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sebLaunches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        help_text="The one-time token embedded in the config's startURL, exchanged for a session inside SEB.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sebLaunches",
                        to="core.onetimetoken",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["quiz", "student"],
                        name="core_quizse_quiz_id_214294_idx",
                    )
                ],
            },
        ),
    ]
