# Generated by Django 6.0.4 on 2026-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0138_quizaccommodation_sebexempt_quizseblaunch"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="publishAt",
            field=models.DateTimeField(
                blank=True,
                help_text="Visible/Preview assignments auto-publish at this time (checked every few minutes).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="publishedAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the assignment last entered the published state. Cleared if it moves back to a pre-published state (not on close/archive).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="scheduledPublishRanAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the scheduled publishAt run last fired (one-shot stamp). Moving publishAt past this re-arms the run.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("visible", "Visible"),
                    ("preview", "Preview"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Lifecycle state: draft -> visible -> preview -> published -> closed -> archived. Students see visible through closed, download files from preview onward, and submit only while published.",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "state"], name="core_assign_course__2d3f3d_idx"
            ),
        ),
    ]
