# Generated by Django 6.0.4 on 2026-08-10 19:46
# Phase 4 of the assignment lifecycle: Assignment.state (0139/0140) is the sole source of
# truth, so the legacy isVisible/isReleased columns are dropped. Reversing re-adds them
# with model defaults only — run 0140's backward step afterwards to re-derive real values
# from state.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_backfill_assignment_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="isReleased",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="isVisible",
        ),
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("assignment_state_changed", "Assignment State Changed"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_access_code_changed", "Quiz Access Code Changed"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_started_late", "Quiz Attempt Started Late"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempt_seb_blocked", "Quiz Attempt SEB Blocked"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_response_graded", "Quiz Response Graded"),
                    ("quiz_response_grade_reopened", "Quiz Response Grade Reopened"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_unapproved",
                        "Generated Question Set Unapproved",
                    ),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
    ]
