# Generated by Django 6.0.4 on 2026-08-11 16:51
# Feedback axis (Phase 5): Assignment.feedbackStatus replaces the feedbackReleased /
# liveFeedbackMode booleans. Operations run add -> backfill -> remove (the
# 0120_split_show_correct_answers pattern), so the backfill's historical model sees both
# old and new fields. Mapping is lossless: live wins over released; hideGrades is an
# orthogonal modifier and is untouched.

from django.db import migrations, models


def backfill_feedback_status(apps, schema_editor):
    Assignment = apps.get_model("core", "Assignment")
    Assignment.objects.filter(liveFeedbackMode=True).update(feedbackStatus="live")
    Assignment.objects.filter(liveFeedbackMode=False, feedbackReleased=True).update(
        feedbackStatus="released")
    # Everything else keeps the field default: hidden.


def rederive_booleans(apps, schema_editor):
    Assignment = apps.get_model("core", "Assignment")
    Assignment.objects.filter(feedbackStatus="live").update(liveFeedbackMode=True)
    Assignment.objects.filter(feedbackStatus="released").update(feedbackReleased=True)
    # per_student has no boolean equivalent — reverses to hidden (both False).


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_remove_assignment_isreleased_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="feedbackStatus",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("live", "Live"),
                    ("per_student", "Per student"),
                    ("released", "Released"),
                ],
                default="hidden",
                help_text="How grading becomes visible to students: hidden (nothing), live (as it's written), per_student (each student once their submission is finalized), released (finalized submissions, globally).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="releaseFeedbackAt",
            field=models.DateTimeField(
                blank=True,
                help_text="Hidden/per-student assignments auto-release feedback at this time (checked every few minutes).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="scheduledFeedbackReleaseRanAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the scheduled releaseFeedbackAt run last fired (one-shot stamp). Moving releaseFeedbackAt past this re-arms the run.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_feedback_status, rederive_booleans),
        migrations.RemoveField(
            model_name="assignment",
            name="feedbackReleased",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="liveFeedbackMode",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="feedbackReleasedAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When feedbackStatus last entered 'released'. Anchors quiz close times relative to feedback release.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="hideGrades",
            field=models.BooleanField(
                default=False,
                help_text="A boolean field. If True, numeric grades are masked from students in any revealing feedbackStatus — they still see comments and the rubric.",
            ),
        ),
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("assignment_state_changed", "Assignment State Changed"),
                    ("assignment_feedback_changed", "Assignment Feedback Changed"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_access_code_changed", "Quiz Access Code Changed"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_started_late", "Quiz Attempt Started Late"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempt_seb_blocked", "Quiz Attempt SEB Blocked"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_response_graded", "Quiz Response Graded"),
                    ("quiz_response_grade_reopened", "Quiz Response Grade Reopened"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_unapproved",
                        "Generated Question Set Unapproved",
                    ),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
    ]
