# Generated by Django 6.0.4 on 2026-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_remove_assignment_feedbackreleased_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapikey",
            name="scope",
            field=models.CharField(
                choices=[
                    ("read", "Read only"),
                    ("write", "Read and write (no deletes, no student email)"),
                    ("admin", "Full course admin (deletes, resets, student email)"),
                ],
                default="read",
                help_text="How much this key may do. Agent tools are filtered by it: a key never even sees the tools above its scope. 'read' is the safe default.",
                max_length=8,
            ),
        ),
    ]
