# Generated by Django 6.0.4 on 2026-08-19 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_alter_courseauditevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutograderExecutionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cached",
                    models.BooleanField(
                        help_text="True if served from cache, False if actually executed"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="Whether the execution (or cached result) succeeded"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Environment language at execution time",
                        max_length=25,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("file_run", "File Run"),
                            ("submission_run", "Submission Run"),
                            ("test_run", "Test Run"),
                        ],
                        help_text="Which execution path produced this event",
                        max_length=20,
                    ),
                ),
                (
                    "error_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("timeout", "Timeout"),
                            ("missing_dependency", "Missing Dependency"),
                            ("compile_error", "Compile Error"),
                            ("runtime_error", "Runtime Error"),
                            ("marker_extraction", "Marker Extraction"),
                            ("infra", "Infrastructure"),
                            ("unknown", "Unknown"),
                        ],
                        default="",
                        help_text="Classified error category for failed executions",
                        max_length=32,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Truncated sample of the error output",
                        max_length=500,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment this execution belonged to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autograder_execution_events",
                        to="core.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="The course this execution belonged to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autograder_execution_events",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created"], name="core_autogr_created_794aea_idx"
                    ),
                    models.Index(
                        fields=["course", "created"],
                        name="core_autogr_course__a69452_idx",
                    ),
                ],
            },
        ),
    ]
