# Generated by Django 6.0.4 on 2026-08-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_autograderexecutionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="gradersCanGenerate",
            field=models.BooleanField(
                default=False,
                help_text="If true, graders may trigger the Generate-missing backfill on this quiz (generation spends AI credits), letting them generate, review, and release sets for their section; if false, only course admins may generate.",
            ),
        ),
    ]
