# Generated by Django 6.0.4 on 2026-08-20 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_quiz_graderscangenerate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="gradersCanGradeQuizzes",
            field=models.BooleanField(
                default=True,
                help_text="A boolean field. If True (default), all course graders may view and grade quiz attempts. If False, quiz grading is restricted to course admins and the designated quizGraders.",
            ),
        ),
        migrations.AddField(
            model_name="quizresponse",
            name="gradedAt",
            field=models.DateTimeField(
                blank=True,
                help_text="When the manual grade was recorded. Null until manually graded; cleared when the response is reopened.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="quizGraders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Graders explicitly allowed to grade quizzes when gradersCanGradeQuizzes is off. Course admins can always grade quizzes.",
                related_name="quizGrader_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
