# Generated by Django 6.0.4 on 2026-08-26 14:51

import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0148_backfill_quizresponse_gradedat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAgentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tool",
                    models.CharField(help_text="The agent tool name.", max_length=64),
                ),
                (
                    "args_hash",
                    models.CharField(
                        help_text="SHA-256 of the canonicalised tool arguments.",
                        max_length=64,
                    ),
                ),
                (
                    "plan_hash",
                    models.CharField(
                        help_text="Fingerprint of the computed plan; a changed plan kills the code.",
                        max_length=32,
                    ),
                ),
                (
                    "plan",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Human-readable plan summary rendered in the dashboard panel.",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The short confirmation code shown in the dashboard.",
                        max_length=12,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Codes die quietly after this."),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once the code is used; a redeemed code never works again.",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course the action would run in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_agent_actions",
                        to="core.course",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The principal the agent was acting as (service account or instructor).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_agent_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["course", "expires_at"],
                        name="core_pendin_course__d74aa5_idx",
                    )
                ],
            },
        ),
    ]
