# Generated by Django 6.0.4 on 2026-08-27 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_pendingagentaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingagentaction",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when a course admin clicks Approve in the dashboard.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingagentaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The course admin who approved it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_agent_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingagentaction",
            name="denied_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when a course admin clicks Deny; blocks re-requests until expiry.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("assignment_state_changed", "Assignment State Changed"),
                    ("assignment_feedback_changed", "Assignment Feedback Changed"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_access_code_changed", "Quiz Access Code Changed"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_started_late", "Quiz Attempt Started Late"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempt_seb_blocked", "Quiz Attempt SEB Blocked"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_response_graded", "Quiz Response Graded"),
                    ("quiz_response_grade_reopened", "Quiz Response Grade Reopened"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_unapproved",
                        "Generated Question Set Unapproved",
                    ),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                    ("agent_write", "Agent Write"),
                    ("agent_write_denied", "Agent Write Denied"),
                    ("agent_action_approved", "Agent Action Approved"),
                    ("agent_action_denied", "Agent Action Denied"),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pendingagentaction",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unused legacy field (pre-approval-button confirmation code).",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pendingagentaction",
            name="expires_at",
            field=models.DateTimeField(help_text="Requests die quietly after this."),
        ),
        migrations.AlterField(
            model_name="pendingagentaction",
            name="plan_hash",
            field=models.CharField(
                help_text="Fingerprint of the computed plan; a changed plan kills the approval.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pendingagentaction",
            name="redeemed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once the approval is consumed; it never authorises again.",
                null=True,
            ),
        ),
    ]
