# Generated by Django 6.1 on 2026-10-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_courseapikey_scope_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submission_attempt", "Submission Attempt"),
                    ("submission_failed", "Submission Failed"),
                    ("file_view", "File View"),
                    ("feedback_view", "Feedback View"),
                    ("regrade_request", "Regrade Request"),
                    ("regrade_deleted", "Regrade Deleted"),
                    ("autograder_triggered", "Autograder Triggered"),
                    ("autograder_completed", "Autograder Completed"),
                    ("autograder_failed", "Autograder Failed"),
                    ("late_day_used", "Late Day Used"),
                    ("comment_feedback", "Comment Feedback"),
                    ("assignment_state_changed", "Assignment State Changed"),
                    ("assignment_feedback_changed", "Assignment Feedback Changed"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_published", "Quiz Published"),
                    ("quiz_unpublished", "Quiz Unpublished"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("quiz_access_code_changed", "Quiz Access Code Changed"),
                    ("quiz_attempt_started", "Quiz Attempt Started"),
                    ("quiz_attempt_started_late", "Quiz Attempt Started Late"),
                    ("quiz_attempt_submitted", "Quiz Attempt Submitted"),
                    ("quiz_attempt_autosubmitted", "Quiz Attempt Auto-Submitted"),
                    ("quiz_attempt_seb_blocked", "Quiz Attempt SEB Blocked"),
                    ("quiz_attempts_reset", "Quiz Attempts Reset"),
                    ("quiz_attempt_deleted", "Quiz Attempt Deleted"),
                    ("quiz_response_graded", "Quiz Response Graded"),
                    ("quiz_response_grade_reopened", "Quiz Response Grade Reopened"),
                    ("quiz_generated_set_approved", "Generated Question Set Approved"),
                    (
                        "quiz_generated_set_unapproved",
                        "Generated Question Set Unapproved",
                    ),
                    (
                        "quiz_generated_set_regenerated",
                        "Generated Question Set Regenerated",
                    ),
                    (
                        "quiz_generated_sets_published",
                        "Generated Question Sets Published",
                    ),
                    ("agent_write", "Agent Write"),
                    ("agent_write_denied", "Agent Write Denied"),
                    ("agent_action_approved", "Agent Action Approved"),
                    ("agent_action_denied", "Agent Action Denied"),
                ],
                help_text="The type of event",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="assignmentTrigger",
            field=models.CharField(
                choices=[
                    ("during", "During the assignment"),
                    ("after_assignment", "After the assignment closes"),
                    ("after_submission", "After the student submits"),
                    ("after_feedback", "After feedback is released (whole assignment)"),
                    (
                        "after_student_feedback",
                        "After each student's feedback is ready (self-paced)",
                    ),
                    ("fixed_date", "At a fixed date & time"),
                ],
                default="during",
                help_text="When an attached quiz becomes available, relative to the assignment lifecycle. Ignored for standalone quizzes.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="availableFrom",
            field=models.DateTimeField(
                blank=True,
                help_text="When the quiz opens — standalone quizzes, or attached quizzes whose assignmentTrigger is 'fixed_date'.",
                null=True,
            ),
        ),
    ]
