# Generated by Django 6.1 on 2026-10-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0152_quiz_fixed_date_trigger_attempt_deleted_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="error_detail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full error output (stderr / executor error), truncated",
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="execution_time",
            field=models.FloatField(
                blank=True,
                help_text="Execution time in seconds, when reported by the executor",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="The file that was executed, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autograder_execution_events",
                to="core.file",
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="file_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of the executed file's name",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="image_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of the environment's Docker image at execution time",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                help_text="The submission this execution belonged to, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autograder_execution_events",
                to="core.submission",
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="task_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Celery task id, for correlating with worker logs",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="autograderexecutionevent",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user whose request triggered this execution, if known",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
