# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rutgers Non-Commercial License, included with this software.
# Generated by Django 5.2.4 on 2025-07-12 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('courseID', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('meta', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedAutograderRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('started', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ended', models.DateTimeField(blank=True, editable=False, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('errors', models.TextField(blank=True)),
                ('test_case_set', models.CharField(choices=[('all', 'all'), ('partial', 'partial')], max_length=255)),
                ('run_by_role', models.CharField(choices=[('instructor', 'instructor'), ('student', 'student'), ('unknown', 'unknown')], default='unknown', max_length=255)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assignment')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.submission')),
            ],
            options={
                'ordering': ['-ended'],
            },
        ),
    ]
