# Generated by Django 2.1.5 on 2020-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('courseID', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('meta', models.TextField(default='')),
            ],
        ),
    ]
