# Generated by Django 5.2.4 on 2025-12-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_alter_event_id_alter_trackedautograderrun_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
