# Generated by Django 6.0.2 on 2026-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0003_alter_event_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("audit", "Audit"), ("activity", "Activity")],
                db_index=True,
                default="activity",
                max_length=20,
            ),
        ),
    ]
