# Generated by Django 2.1.2 on 2019-12-09 02:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('core', '0049_auto_20191209_0222'),
  ]

  operations = [
      migrations.CreateModel(
          name='Credit',
          fields=[
              ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('stripePaymentIntentId', models.TextField(default='')),
              ('rating', models.IntegerField(default=0)),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='Order',
          fields=[
              ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('userStripeCustomerIdBackup', models.TextField(blank=True, default='')),
              ('stripeSessionId', models.TextField(blank=True, default='')),
              ('baseRate', models.IntegerField(default=0)),
              ('discountRate', models.DecimalField(decimal_places=2, max_digits=4, validators=[
               django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
              ('reviewRate', models.IntegerField(default=0)),
              ('status', django_fsm.FSMField(default='created', max_length=50, protected=True)),
              ('assignments', models.ManyToManyField(related_name='assignment_orders', to='core.Assignment')),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='Payout',
          fields=[
              ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('completedAt', models.DateTimeField(blank=True, null=True)),
              ('status', django_fsm.FSMField(default='pending', max_length=50, protected=True)),
              ('reviewer', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
          ],
          options={
              'abstract': False,
          },
      ),
      # migrations.CreateModel(
      #     name='Product',
      #     fields=[
      #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      #         ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
      #         ('modified', models.DateTimeField(default=django.utils.timezone.now)),
      #         ('name', models.TextField(unique=True)),
      #         ('url', models.TextField(blank=True, default='')),
      #         ('offeredBy', models.TextField(blank=True, default='')),
      #         ('cBaseRate', models.IntegerField(default=0)),
      #         ('cDiscountRate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
      #         ('cReviewRate', models.IntegerField(default=0)),
      #         ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Course')),
      #     ],
      #     options={
      #         'abstract': False,
      #     },
      # ),
      # migrations.CreateModel(
      #     name='Review',
      #     fields=[
      #         ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
      #         ('modified', models.DateTimeField(default=django.utils.timezone.now)),
      #         ('credit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mooc.Credit')),
      #         ('approved', models.BooleanField(default=False)),
      #         ('approvedAt', models.DateTimeField(blank=True, null=True)),
      #         ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooc.Payout')),
      #         ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
      #     ],
      # ),
      # migrations.AddField(
      #     model_name='order',
      #     name='product',
      #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mooc.Product'),
      # ),
      # migrations.AddField(
      #     model_name='order',
      #     name='user',
      #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
      # ),
      # migrations.AddField(
      #     model_name='credit',
      #     name='assignment',
      #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='core.Assignment'),
      # ),
      # migrations.AddField(
      #     model_name='credit',
      #     name='order',
      #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mooc.Order'),
      # ),
      # migrations.AddField(
      #     model_name='credit',
      #     name='submission',
      #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Submission'),
      # ),
      # migrations.AddField(
      #     model_name='credit',
      #     name='user',
      #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
      # ),
      # migrations.AlterUniqueTogether(
      #     name='review',
      #     unique_together={('credit', 'reviewer')},
      # ),
  ]
