# Generated by Django 2.1.2 on 2019-12-09 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('mooc', '0001_initial'),
  ]

  operations = [
      migrations.CreateModel(
          name='Product',
          fields=[
              ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('name', models.TextField(default='')),
              ('url', models.TextField(blank=True, default='')),
              ('offeredBy', models.TextField(blank=True, default='')),
              ('cBaseRate', models.IntegerField(default=0)),
              ('cDiscountRate', models.DecimalField(decimal_places=2, max_digits=4, validators=[
               django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
              ('cReviewRate', models.IntegerField(default=0)),
              ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Course')),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='Review',
          fields=[
              ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
              ('modified', models.DateTimeField(default=django.utils.timezone.now)),
              ('credit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                              primary_key=True, serialize=False, to='mooc.Credit')),
              ('approved', models.BooleanField(default=False)),
              ('approvedAt', models.DateTimeField(blank=True, null=True)),
              ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mooc.Payout')),
              ('reviewer', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
          ],
      ),
      migrations.AddField(
          model_name='credit',
          name='assignment',
          field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                  related_name='credits', to='core.Assignment'),
      ),
      migrations.AddField(
          model_name='credit',
          name='order',
          field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mooc.Order'),
      ),
      migrations.AddField(
          model_name='credit',
          name='submission',
          field=models.OneToOneField(
              blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Submission'),
      ),
      migrations.AddField(
          model_name='credit',
          name='user',
          field=models.ForeignKey(blank=True, null=True,
                                  on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
      ),
      migrations.AddField(
          model_name='order',
          name='user',
          field=models.ForeignKey(blank=True, null=True,
                                  on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
      ),
      migrations.AddField(
          model_name='order',
          name='product',
          field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mooc.Product'),
      ),
      migrations.AlterUniqueTogether(
          name='review',
          unique_together={('credit', 'reviewer')},
      ),
  ]
