# Generated by Django 2.1.2 on 2019-12-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0002_auto_20191209_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mooc.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mooc.Product'),
        ),
    ]
