# Generated by Django 2.1.2 on 2019-12-25 00:08

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

  dependencies = [
      ('mooc', '0003_auto_20191209_0510'),
  ]

  operations = [
      migrations.AlterField(
          model_name='payout',
          name='status',
          field=django_fsm.FSMField(default='pending', max_length=50),
      ),
      migrations.AlterField(
          model_name='review',
          name='payout',
          field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                  related_name='reviews', to='mooc.Payout'),
      ),
  ]
