# Generated by Django 2.1.5 on 2020-05-07 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0004_auto_20191225_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(blank=True, default='Basic Tier')),
                ('description', models.TextField(default='')),
                ('rateTotal', models.IntegerField(default=0, help_text='Total (cents)')),
                ('rateReview', models.IntegerField(default=0, help_text='Rate paid to reviewer (cents)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='mooc.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='rateReview',
            field=models.IntegerField(default=0, help_text='Rate paid to reviewer (cents)'),
        ),
        migrations.AddField(
            model_name='order',
            name='rateTotal',
            field=models.IntegerField(default=0, help_text='Total (cents)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mooc.Tier'),
        ),
    ]
