# Copyright © 2026 Rutgers, the State University of New Jersey. All rights reserved except as defined by the Rurtgers Non-Commercial Licensed, included with this software.
import json
import logging
from typing import Set, Optional
from .base import BaseFileHandler

logger = logging.getLogger(__name__)

class NodeHandler(BaseFileHandler):
    
    def get_language(self) -> str:
        return 'node-20'

    def is_executable(self) -> bool:
        return True

    def get_requirements(self) -> Optional[str]:
        if self.file.name == 'package.json':
            content = self.content
            try:
                # Basic validation
                json.loads(content)
                return content
            except json.JSONDecodeError:
                pass
                
        imports = self.scan_content(self.content)
        if not imports:
            return None
            
        filtered = {p for p in imports if not p.startswith('.')} 
        if filtered:
             mock_pkg = {
                 "name": "autogenerated-project",
                 "version": "1.0.0",
                 "dependencies": {p: "*" for p in sorted(filtered)}
             }
             return json.dumps(mock_pkg, indent=2)
        return None

    @classmethod
    def scan_content(cls, code: str) -> Set[str]:
        packages = set()
        try:
            import esprima
            # Parse module
            tree = esprima.parseModule(code)
            
            # Simple recursive visitor
            def visit(node):
                if not node or not hasattr(node, 'type'): return
                
                # Handle CJS require
                if node.type == 'CallExpression':
                    if hasattr(node.callee, 'name') and node.callee.name == 'require':
                        if node.arguments and node.arguments[0].type == 'Literal':
                            packages.add(node.arguments[0].value)
                
                # Handle ESM import
                if node.type == 'ImportDeclaration':
                    if hasattr(node.source, 'value'):
                        packages.add(node.source.value)
                
                # Recurse
                for key, value in node.__dict__.items():
                    if isinstance(value, list):
                        for item in value:
                            visit(item)
                    elif hasattr(value, 'type'):
                        visit(value)
                        
            visit(tree)
        except ImportError:
            pass # esprima not installed
        except Exception:
            pass # parse error
        return packages
