name: Deploy to Production Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        environment: production
        runs-on: production-api
        env:
            DEBUG: true
            API_URL: ${{ vars.API_URL }}
            CLIENT_URL: ${{ vars.CLIENT_URL }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            ROOT_DATABASE_PASSWORD: ${{ secrets.ROOT_DATABASE_PASSWORD }}
            API_USER: ${{ secrets.API_USER }}
            API_PASSWORD: ${{ secrets.API_PASSWORD }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            EMAIL_HOST: ${{ vars.EMAIL_HOST }}
            EMAIL_PORT: ${{ vars.EMAIL_PORT }}
            EMAIL_USE_TLS: ${{ vars.EMAIL_USE_TLS }}
            EMAIL_USE_SSL: ${{ vars.EMAIL_USE_SSL }}
            DEFAULT_EMAIL_FROM: ${{ vars.DEFAULT_EMAIL_FROM }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Certs
              run: |
                  HOSTNAME=$(hostname)
                  ln -s /etc/letsencrypt/live/$HOSTNAME certs

            - name: Set up .env
              run: |
                  cat <<EOF > .env
                  DEBUG=${{ env.DEBUG }}
                  API_URL=${{ vars.API_URL }}
                  CLIENT_URL=${{ vars.CLIENT_URL }}
                  SECRET_KEY=${{ secrets.SECRET_KEY }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  ROOT_DATABASE_PASSWORD=${{ secrets.ROOT_DATABASE_PASSWORD }}
                  API_USER=${{ secrets.API_USER }}
                  API_PASSWORD=${{ secrets.API_PASSWORD }}
                  EMAIL_HOST=${{ vars.EMAIL_HOST }}
                  EMAIL_PORT=${{ vars.EMAIL_PORT }}
                  EMAIL_USE_TLS=${{ vars.EMAIL_USE_TLS }}
                  EMAIL_USE_SSL=${{ vars.EMAIL_USE_SSL }}
                  DEFAULT_EMAIL_FROM=${{ vars.DEFAULT_EMAIL_FROM }}
                  EOF

            - name: Build and deploy
              run: |
                  docker compose build
                  docker compose up -d --remove-orphans

            - name: Remove docker artifacts
              run: |
                  docker system prune -f

            - name: Notify deployment success
              run: echo "Deployment to development server successful!"
